# Generated by Django 4.2.30 on 2026-05-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoquePCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código do Produto')),
                ('data_movimentacao', models.DateField(db_index=True, verbose_name='Data da Movimentação')),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('origem_movimentacao', models.CharField(choices=[('NF_ENTRADA', 'Nota Fiscal de Entrada'), ('NF_SAIDA', 'Nota Fiscal de Saída'), ('MOV_INTERNA', 'Movimentação Interna')], max_length=20, verbose_name='Origem da Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Quantidade')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento de Origem')),
                ('cf_operacao', models.CharField(blank=True, max_length=5, null=True, verbose_name='CF da Operação (SD3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque (PCP)',
                'verbose_name_plural': 'Movimentações de Estoque (PCP)',
                'indexes': [models.Index(fields=['produto_codigo', 'data_movimentacao'], name='pcp_movimen_produto_673ca1_idx')],
                'unique_together': {('produto_codigo', 'data_movimentacao', 'documento', 'origem_movimentacao', 'cf_operacao')},
            },
        ),
    ]
