# Generated by Django 4.2.30 on 2026-06-03 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcpAreaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Codigo')),
                ('nome', models.CharField(db_index=True, max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Area de Producao',
                'verbose_name_plural': 'Areas de Producao',
                'db_table': 'pcp_area_producao',
            },
        ),
        migrations.CreateModel(
            name='PcpAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Codigo')),
                ('nome', models.CharField(db_index=True, max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('fabricante', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Numero de Serie')),
                ('status', models.CharField(choices=[('operando', 'Operando'), ('parado', 'Parado'), ('manutencao', 'Em manutencao'), ('inativo', 'Inativo')], db_index=True, default='operando', max_length=20, verbose_name='Status')),
                ('criticidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], db_index=True, default='media', max_length=20, verbose_name='Criticidade')),
            ],
            options={
                'verbose_name': 'Ativo PCP',
                'verbose_name_plural': 'Ativos PCP',
                'db_table': 'pcp_ativo',
            },
        ),
        migrations.CreateModel(
            name='PcpDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('nao_planejado', 'Nao planejado'), ('planejado', 'Planejado'), ('setup', 'Setup'), ('qualidade', 'Qualidade'), ('falta_material', 'Falta de material'), ('manutencao', 'Manutencao')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('inicio', models.DateTimeField(db_index=True, verbose_name='Inicio')),
                ('fim', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fim')),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Duracao em minutos')),
                ('motivo', models.CharField(db_index=True, max_length=255, verbose_name='Motivo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('celery', 'Celery'), ('etl', 'ETL'), ('sistema', 'Sistema')], db_index=True, default='manual', max_length=20, verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Downtime PCP',
                'verbose_name_plural': 'Downtimes PCP',
                'db_table': 'pcp_downtime',
            },
        ),
        migrations.CreateModel(
            name='PcpExecucaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva'), ('inspecao', 'Inspecao')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('data_inicio', models.DateTimeField(db_index=True, verbose_name='Data de inicio')),
                ('data_fim', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de fim')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
            ],
            options={
                'verbose_name': 'Execucao de Manutencao',
                'verbose_name_plural': 'Execucoes de Manutencao',
                'db_table': 'pcp_execucao_manutencao',
            },
        ),
        migrations.CreateModel(
            name='PcpParametroAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dias_antecedencia', models.PositiveIntegerField(default=7, verbose_name='Dias de antecedencia')),
                ('emails_destino', models.TextField(verbose_name='Emails destino')),
                ('alertar_preventiva', models.BooleanField(default=True, verbose_name='Alertar preventiva')),
                ('alertar_downtime_aberto', models.BooleanField(default=True, verbose_name='Alertar downtime aberto')),
            ],
            options={
                'verbose_name': 'Parametro de Alerta PCP',
                'verbose_name_plural': 'Parametros de Alerta PCP',
                'db_table': 'pcp_parametro_alerta',
            },
        ),
        migrations.CreateModel(
            name='PcpPlanoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva'), ('inspecao', 'Inspecao')], db_index=True, default='preventiva', max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(db_index=True, max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo em dias')),
                ('intervalo_horas_operacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Intervalo em horas de operacao')),
            ],
            options={
                'verbose_name': 'Plano de Manutencao',
                'verbose_name_plural': 'Planos de Manutencao',
                'db_table': 'pcp_plano_manutencao',
            },
        ),
        migrations.CreateModel(
            name='PcpProgramacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_prevista', models.DateField(db_index=True, verbose_name='Data prevista')),
                ('data_limite', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data limite')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_execucao', 'Em execucao'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada'), ('atrasada', 'Atrasada')], db_index=True, default='planejada', max_length=20, verbose_name='Status')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('celery', 'Celery'), ('etl', 'ETL'), ('sistema', 'Sistema')], db_index=True, default='sistema', max_length=20, verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Programacao de Manutencao',
                'verbose_name_plural': 'Programacoes de Manutencao',
                'db_table': 'pcp_programacao_manutencao',
            },
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoquepcp',
            options={'verbose_name': 'Movimentacao de Estoque (PCP)', 'verbose_name_plural': 'Movimentacoes de Estoque (PCP)'},
        ),
        migrations.RenameIndex(
            model_name='movimentacaoestoquepcp',
            new_name='pcp_mov_produto_data_idx',
            old_name='pcp_movimen_produto_673ca1_idx',
        ),
        migrations.AddField(
            model_name='movimentacaoestoquepcp',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='cf_operacao',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CF da Operacao (SD3)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='data_movimentacao',
            field=models.DateField(db_index=True, verbose_name='Data da Movimentacao'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='documento',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Documento de Origem'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='origem_movimentacao',
            field=models.CharField(choices=[('NF_ENTRADA', 'Nota Fiscal de Entrada'), ('NF_SAIDA', 'Nota Fiscal de Saida'), ('MOV_INTERNA', 'Movimentacao Interna')], db_index=True, max_length=20, verbose_name='Origem da Movimentacao'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='produto_codigo',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Codigo do Produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], db_index=True, max_length=10, verbose_name='Tipo de Movimentacao'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoquepcp',
            index=models.Index(fields=['ativo', 'data_movimentacao'], name='pcp_mov_ativo_data_idx'),
        ),
        migrations.AlterModelTable(
            name='movimentacaoestoquepcp',
            table='pcp_movimentacaoestoquepcp',
        ),
        migrations.AddField(
            model_name='pcpprogramacaomanutencao',
            name='ativo_pcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes_manutencao', to='pcp.pcpativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='pcpprogramacaomanutencao',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='pcp.pcpplanomanutencao', verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='pcpplanomanutencao',
            name='ativo_pcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_manutencao', to='pcp.pcpativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='pcpparametroalerta',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametros_alerta', to='pcp.pcpareaproducao', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='pcpparametroalerta',
            name='ativo_pcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametros_alerta', to='pcp.pcpativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='ativo_pcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes_manutencao', to='pcp.pcpativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='programacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='pcp.pcpprogramacaomanutencao', verbose_name='Programacao'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_manutencao_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel'),
        ),
        migrations.AddField(
            model_name='pcpdowntime',
            name='ativo_pcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='pcp.pcpativo', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='pcpdowntime',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel'),
        ),
        migrations.AddField(
            model_name='pcpativo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='pcp.pcpareaproducao', verbose_name='Area de Producao'),
        ),
        migrations.AddIndex(
            model_name='pcpareaproducao',
            index=models.Index(fields=['codigo'], name='pcp_area_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpareaproducao',
            index=models.Index(fields=['nome'], name='pcp_area_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpareaproducao',
            index=models.Index(fields=['ativo'], name='pcp_area_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpprogramacaomanutencao',
            index=models.Index(fields=['ativo_pcp', 'data_prevista'], name='pcp_prog_ativo_data_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpprogramacaomanutencao',
            index=models.Index(fields=['plano', 'status'], name='pcp_prog_plano_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpprogramacaomanutencao',
            index=models.Index(fields=['status', 'data_prevista'], name='pcp_prog_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpprogramacaomanutencao',
            index=models.Index(fields=['ativo', 'data_prevista'], name='pcp_prog_ativo_flag_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='pcpprogramacaomanutencao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('plano', 'data_prevista'), name='pcp_programacao_plano_data_uniq'),
        ),
        migrations.AddIndex(
            model_name='pcpplanomanutencao',
            index=models.Index(fields=['ativo_pcp', 'ativo'], name='pcp_plano_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpplanomanutencao',
            index=models.Index(fields=['tipo', 'ativo'], name='pcp_plano_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpplanomanutencao',
            index=models.Index(fields=['nome'], name='pcp_plano_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpparametroalerta',
            index=models.Index(fields=['ativo_pcp', 'ativo'], name='pcp_alerta_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpparametroalerta',
            index=models.Index(fields=['area', 'ativo'], name='pcp_alerta_area_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpexecucaomanutencao',
            index=models.Index(fields=['ativo_pcp', 'data_inicio'], name='pcp_exec_ativo_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpexecucaomanutencao',
            index=models.Index(fields=['tipo', 'data_inicio'], name='pcp_exec_tipo_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpexecucaomanutencao',
            index=models.Index(fields=['responsavel', 'data_inicio'], name='pcp_exec_resp_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpdowntime',
            index=models.Index(fields=['ativo_pcp', 'inicio'], name='pcp_down_ativo_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpdowntime',
            index=models.Index(fields=['tipo', 'inicio'], name='pcp_down_tipo_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpdowntime',
            index=models.Index(fields=['fim', 'ativo'], name='pcp_down_fim_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpdowntime',
            index=models.Index(fields=['origem', 'inicio'], name='pcp_down_origem_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpativo',
            index=models.Index(fields=['codigo'], name='pcp_ativo_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpativo',
            index=models.Index(fields=['nome'], name='pcp_ativo_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpativo',
            index=models.Index(fields=['area', 'ativo'], name='pcp_ativo_area_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpativo',
            index=models.Index(fields=['status', 'ativo'], name='pcp_ativo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpativo',
            index=models.Index(fields=['criticidade', 'ativo'], name='pcp_ativo_criticidade_idx'),
        ),
    ]
