# Generated by Django 4.2.30 on 2026-06-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0002_pcpareaproducao_pcpativo_pcpdowntime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcpAlertaEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_alerta', models.CharField(choices=[('preventiva', 'Preventiva'), ('downtime_aberto', 'Downtime aberto')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('chave_idempotencia', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Chave de idempotencia')),
                ('data_referencia', models.DateField(db_index=True, verbose_name='Data de referencia')),
                ('destinatarios', models.TextField(verbose_name='Destinatarios')),
                ('assunto', models.CharField(max_length=180, verbose_name='Assunto')),
                ('enviado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Enviado em')),
                ('downtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_enviados', to='pcp.pcpdowntime', verbose_name='Downtime')),
                ('parametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_enviados', to='pcp.pcpparametroalerta', verbose_name='Parametro')),
                ('programacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_enviados', to='pcp.pcpprogramacaomanutencao', verbose_name='Programacao')),
            ],
            options={
                'verbose_name': 'Alerta Enviado PCP',
                'verbose_name_plural': 'Alertas Enviados PCP',
                'db_table': 'pcp_alerta_enviado',
                'indexes': [models.Index(fields=['tipo_alerta', 'data_referencia'], name='pcp_alerta_env_tipo_data_idx'), models.Index(fields=['enviado_em', 'ativo'], name='pcp_alerta_env_enviado_idx')],
            },
        ),
    ]
