# Generated by Django 4.2.30 on 2026-06-04 16:37

from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Abs


def normalizar_dados_existentes(apps, schema_editor):
    Movimentacao = apps.get_model("pcp", "MovimentacaoEstoquePCP")
    Alerta = apps.get_model("pcp", "PcpAlertaEnviado")
    Downtime = apps.get_model("pcp", "PcpDowntime")
    Execucao = apps.get_model("pcp", "PcpExecucaoManutencao")
    ParametroAlerta = apps.get_model("pcp", "PcpParametroAlerta")
    Plano = apps.get_model("pcp", "PcpPlanoManutencao")
    Programacao = apps.get_model("pcp", "PcpProgramacaoManutencao")

    Movimentacao.objects.filter(documento__isnull=True).update(documento="")
    Movimentacao.objects.filter(cf_operacao__isnull=True).update(cf_operacao="")
    Movimentacao.objects.filter(quantidade__lt=0).update(quantidade=Abs("quantidade"))

    Alerta.objects.filter(enviado_em__isnull=False).update(status="enviado", tentativas=1)
    Plano.objects.filter(ativo=True, intervalo_dias__isnull=True).update(ativo=False)
    Programacao.objects.filter(status="atrasada").update(status="planejada")
    Programacao.objects.filter(data_limite__lt=models.F("data_prevista")).update(
        data_limite=models.F("data_prevista")
    )
    ParametroAlerta.objects.filter(ativo_pcp__isnull=False, area__isnull=False).update(area=None)
    Execucao.objects.filter(data_fim__lte=models.F("data_inicio")).update(data_fim=None)
    Downtime.objects.filter(fim__lte=models.F("inicio")).update(fim=None, duracao_minutos=None)

    ativos_com_downtime_duplicado = (
        Downtime.objects.filter(ativo=True, fim__isnull=True)
        .values("ativo_pcp_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for item in ativos_com_downtime_duplicado.iterator():
        ids = list(
            Downtime.objects.filter(ativo=True, fim__isnull=True, ativo_pcp_id=item["ativo_pcp_id"])
            .order_by("-inicio", "-id")
            .values_list("id", flat=True)
        )
        Downtime.objects.filter(id__in=ids[1:]).update(ativo=False)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0003_pcpalertaenviado'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimentacaoestoquepcp',
            name='pcp_mov_produto_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpalertaenviado',
            name='pcp_alerta_env_enviado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpareaproducao',
            name='pcp_area_codigo_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpareaproducao',
            name='pcp_area_nome_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpareaproducao',
            name='pcp_area_ativo_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpativo',
            name='pcp_ativo_codigo_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpativo',
            name='pcp_ativo_nome_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpplanomanutencao',
            name='pcp_plano_nome_idx',
        ),
        migrations.RemoveIndex(
            model_name='pcpprogramacaomanutencao',
            name='pcp_prog_ativo_data_idx',
        ),
        migrations.AlterUniqueTogether(
            name='movimentacaoestoquepcp',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pcpplanomanutencao',
            name='intervalo_horas_operacao',
        ),
        migrations.RemoveField(
            model_name='pcpprogramacaomanutencao',
            name='ativo_pcp',
        ),
        migrations.AddField(
            model_name='movimentacaoestoquepcp',
            name='filial',
            field=models.CharField(db_index=True, default='', max_length=10, verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='pcpalertaenviado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('falha', 'Falha')], db_index=True, default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='pcpalertaenviado',
            name='tentativas',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas'),
        ),
        migrations.AddField(
            model_name='pcpalertaenviado',
            name='ultimo_erro',
            field=models.TextField(blank=True, verbose_name='Ultimo erro'),
        ),
        migrations.RunPython(normalizar_dados_existentes, noop_reverse),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='cf_operacao',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='CF da Operacao (SD3)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='documento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Documento de Origem'),
        ),
        migrations.AlterField(
            model_name='pcpprogramacaomanutencao',
            name='status',
            field=models.CharField(choices=[('planejada', 'Planejada'), ('em_execucao', 'Em execucao'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], db_index=True, default='planejada', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoquepcp',
            index=models.Index(fields=['filial', 'produto_codigo', 'data_movimentacao'], name='pcp_mov_fil_prod_data_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpalertaenviado',
            index=models.Index(fields=['status', 'ativo'], name='pcp_alerta_env_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoquepcp',
            constraint=models.UniqueConstraint(fields=('filial', 'produto_codigo', 'data_movimentacao', 'tipo_movimentacao', 'origem_movimentacao', 'documento', 'cf_operacao'), name='pcp_movimentacao_natural_uniq'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoquepcp',
            constraint=models.CheckConstraint(check=models.Q(('quantidade__gte', 0)), name='pcp_movimentacao_quantidade_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='pcpdowntime',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('fim__isnull', True)), fields=('ativo_pcp',), name='pcp_downtime_aberto_ativo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pcpdowntime',
            constraint=models.CheckConstraint(check=models.Q(('fim__isnull', True), ('fim__gt', models.F('inicio')), _connector='OR'), name='pcp_downtime_fim_gt_inicio'),
        ),
        migrations.AddConstraint(
            model_name='pcpexecucaomanutencao',
            constraint=models.CheckConstraint(check=models.Q(('data_fim__isnull', True), ('data_fim__gt', models.F('data_inicio')), _connector='OR'), name='pcp_execucao_fim_gt_inicio'),
        ),
        migrations.AddConstraint(
            model_name='pcpparametroalerta',
            constraint=models.CheckConstraint(check=models.Q(('area__isnull', False), ('ativo_pcp__isnull', False), _negated=True), name='pcp_parametro_alerta_um_alvo'),
        ),
        migrations.AddConstraint(
            model_name='pcpplanomanutencao',
            constraint=models.CheckConstraint(check=models.Q(('ativo', False), ('intervalo_dias__gt', 0), _connector='OR'), name='pcp_plano_ativo_exige_intervalo'),
        ),
        migrations.AddConstraint(
            model_name='pcpprogramacaomanutencao',
            constraint=models.CheckConstraint(check=models.Q(('data_limite__isnull', True), ('data_limite__gte', models.F('data_prevista')), _connector='OR'), name='pcp_programacao_limite_gte_prevista'),
        ),
    ]
