# Generated by Django 4.2.30 on 2026-06-04 16:41

from django.db import migrations, models
from django.db.models import Count


def normalizar_programacoes_pendentes(apps, schema_editor):
    Programacao = apps.get_model("pcp", "PcpProgramacaoManutencao")
    duplicados = (
        Programacao.objects.filter(ativo=True, status__in=["planejada", "em_execucao"])
        .values("plano_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for item in duplicados.iterator():
        pendentes = Programacao.objects.filter(
            ativo=True,
            plano_id=item["plano_id"],
            status__in=["planejada", "em_execucao"],
        )
        manter = pendentes.filter(status="em_execucao").order_by("data_prevista", "id").first()
        manter = manter or pendentes.order_by("data_prevista", "id").first()
        pendentes.exclude(pk=manter.pk).update(status="cancelada")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0004_remove_movimentacaoestoquepcp_pcp_mov_produto_data_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(normalizar_programacoes_pendentes, noop_reverse),
        migrations.AddConstraint(
            model_name='pcpprogramacaomanutencao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('status__in', ['planejada', 'em_execucao'])), fields=('plano',), name='pcp_programacao_pendente_plano_uniq'),
        ),
    ]
