# Generated by Django 4.2.30 on 2026-06-04 16:43

from django.db import migrations, models
from django.db.models import Count


def normalizar_execucoes_abertas(apps, schema_editor):
    Execucao = apps.get_model("pcp", "PcpExecucaoManutencao")
    duplicados = (
        Execucao.objects.filter(ativo=True, data_fim__isnull=True)
        .values("ativo_pcp_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for item in duplicados.iterator():
        ids = list(
            Execucao.objects.filter(ativo=True, data_fim__isnull=True, ativo_pcp_id=item["ativo_pcp_id"])
            .order_by("-data_inicio", "-id")
            .values_list("id", flat=True)
        )
        Execucao.objects.filter(id__in=ids[1:]).update(ativo=False)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0005_pcpprogramacaomanutencao_pcp_programacao_pendente_plano_uniq'),
    ]

    operations = [
        migrations.RunPython(normalizar_execucoes_abertas, noop_reverse),
        migrations.AddConstraint(
            model_name='pcpexecucaomanutencao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('data_fim__isnull', True)), fields=('ativo_pcp',), name='pcp_execucao_aberta_ativo_uniq'),
        ),
    ]
