# Generated by Django 4.2.30 on 2026-06-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0006_pcpexecucaomanutencao_pcp_execucao_aberta_ativo_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcpparametroalerta',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametros_alerta', to='pcp.pcpareaproducao', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='pcpparametroalerta',
            name='ativo_pcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametros_alerta', to='pcp.pcpativo', verbose_name='Ativo'),
        ),
    ]
