# Generated by Django 4.2.30 on 2026-06-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0012_pcpevidenciamanutencao_finalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcpItemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo_pcp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_manutencao', to='pcp.pcpativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Item de Manutenção',
                'verbose_name_plural': 'Itens de Manutenção',
                'db_table': 'pcp_item_manutencao',
            },
        ),
        migrations.CreateModel(
            name='PcpPlanoManutencaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_planos', to='pcp.pcpitemmanutencao', verbose_name='Item de manutenção')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_planejados', to='pcp.pcpplanomanutencao', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Item do Plano de Manutenção',
                'verbose_name_plural': 'Itens dos Planos de Manutenção',
                'db_table': 'pcp_plano_manutencao_item',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pcpplanomanutencao',
            name='itens_manutencao',
            field=models.ManyToManyField(blank=True, related_name='planos_manutencao', through='pcp.PcpPlanoManutencaoItem', to='pcp.pcpitemmanutencao', verbose_name='Itens de manutenção'),
        ),
        migrations.AddIndex(
            model_name='pcpplanomanutencaoitem',
            index=models.Index(fields=['plano', 'ordem'], name='pcp_plano_item_ordem_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpplanomanutencaoitem',
            index=models.Index(fields=['item_manutencao'], name='pcp_plano_item_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='pcpplanomanutencaoitem',
            constraint=models.UniqueConstraint(fields=('plano', 'item_manutencao'), name='pcp_plano_item_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pcpplanomanutencaoitem',
            constraint=models.UniqueConstraint(fields=('plano', 'ordem'), name='pcp_plano_item_ordem_uniq'),
        ),
        migrations.AddIndex(
            model_name='pcpitemmanutencao',
            index=models.Index(fields=['ativo_pcp', 'ativo'], name='pcp_item_ativo_flag_idx'),
        ),
        migrations.AddConstraint(
            model_name='pcpitemmanutencao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ativo_pcp', 'descricao'), name='pcp_item_manutencao_ativo_desc_uniq'),
        ),
    ]
