from django.urls import path
from . import views

urlpatterns = [
    path('vagas/', views.job_list, name='job_list'),
    path('vagas/<int:pk>/aplicar/', views.job_apply, name='job_apply'),
    path('painel/', views.candidate_screening, name='candidate_screening'),
    path('candidato/<int:pk>/', views.candidate_datail, name='candidate_datail'),
    path('gestao-vagas/', views.job_management, name='job_management'),
    path('gestao-vagas/nova/', views.job_form, name='nova_vaga'),
    path('gestao-vagas/<int:pk>/editar/', views.job_form, name='editar_vaga'),
    path('solicitar-vaga/', views.solicitar_abertura_vaga, name='solicitar_vaga'),
    path('solicitacoes/', views.listar_solicitacoes, name='listar_solicitacoes'),
    path('solicitacoes/<int:pk>/', views.detalhe_solicitacao, name='detalhe_solicitacao'),
    path('pesquisa-demissional/', views.listar_pesquisas, name='listar_pesquisas'),
    path('pesquisa-demissional/gerar/', views.gerar_pesquisa, name='gerar_pesquisa'),
    path('pesquisa-demissional/responder/<uuid:uuid_pesquisa>/', views.responder_pesquisa, name='responder_pesquisa'),
    path('avaliacoes-desempenho/', views.listar_avaliacoes_desempenho, name='listar_avaliacoes_desempenho'),
    path('avaliacoes-desempenho/dashboard-geral/', views.dashboard_geral_avaliacoes_desempenho, name='dashboard_geral_avaliacoes_desempenho'),
    path('avaliacoes-desempenho/nova/', views.nova_avaliacao_desempenho, name='nova_avaliacao_desempenho'),
    path('avaliacoes-desempenho/<int:pk>/', views.detalhe_avaliacao_desempenho, name='detalhe_avaliacao_desempenho'),
    path('avaliacoes-desempenho/<int:pk>/editar/', views.editar_avaliacao_desempenho, name='editar_avaliacao_desempenho'),
    path('avaliacoes-desempenho/<int:pk>/dashboard/', views.dashboard_avaliacao_desempenho, name='dashboard_avaliacao_desempenho'),
    path('avaliacoes-desempenho/<int:pk>/ciencia-gestor/', views.dar_ciencia_gestor_avaliacao, name='dar_ciencia_gestor_avaliacao'),
    path('avaliacoes-desempenho/<int:pk>/ciencia-colaborador/', views.dar_ciencia_colaborador_avaliacao, name='dar_ciencia_colaborador_avaliacao'),
    path('avaliacoes-desempenho/<int:pk>/pdf/', views.exportar_pdf_avaliacao_desempenho, name='exportar_pdf_avaliacao_desempenho'),
    path('formulario-admissional/', views.listar_formularios_admissionais, name='listar_formularios_admissionais'),
    path('formulario-admissional/gerar/', views.gerar_formulario_admissional, name='gerar_formulario_admissional'),
    path('formulario-admissional/<uuid:uuid_formulario>/pdf/', views.exportar_formulario_admissional_pdf, name='exportar_formulario_admissional_pdf'),
    path('formulario-admissional/<uuid:uuid_formulario>/', views.detalhe_formulario_admissional, name='detalhe_formulario_admissional'),
    path('formulario-admissional/responder/<uuid:uuid_formulario>/', views.responder_formulario_admissional, name='responder_formulario_admissional'),
    path('pesquisas/', views.listar_pesquisas, name='listar_pesquisas'),
    path('dashboard/', views.dashboard_rh, name='dashboard_rh'),
    path('dashboard/importar/', views.importar_base_rh, name='importar_base_rh'),
    path('dashboard/importar-ponto/', views.importar_ponto_rh, name='importar_ponto_rh')
]
