# Generated by Django 6.0.2 on 2026-02-27 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Vaga')),
                ('setor', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('COMPRAS', 'Compras'), ('DIRETORIA', 'Diretoria'), ('FINANCEIRO', 'Financeiro'), ('OBRA', 'Obra'), ('ORCAMENTO', 'Orçamento'), ('QUALIDADE', 'Planejamento Processo e Qualidade'), ('PRODUCAO', 'Produção'), ('PROJETOS', 'Projetos'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição das Atividades')),
                ('requisitos', models.TextField(verbose_name='Requisitos e Qualificações')),
                ('ativa', models.BooleanField(default=True, verbose_name='Vaga Aberta (Aceitando currículos)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp / Telefone')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Perfil do LinkedIn')),
                ('curriculo', models.FileField(upload_to='curriculos/%Y/%m/', verbose_name='Currículo (PDF)')),
                ('status', models.CharField(choices=[('NOVO', 'Novo (Aguardando Triagem)'), ('EM_ANALISE', 'Em Análise'), ('ENTREVISTA', 'Em Fase de Entrevista'), ('APROVADO', 'Aprovado (Contratado)'), ('REPROVADO', 'Reprovado / Banco de Talentos')], default='NOVO', max_length=20)),
                ('observacoes_rh', models.TextField(blank=True, verbose_name='Anotações Internas do RH')),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='rh.vaga')),
            ],
        ),
    ]
