# Generated by Django 6.0.2 on 2026-03-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='lgpd_consentimento',
            field=models.BooleanField(default=False, verbose_name='LGPD (Consentimento)'),
        ),
    ]
