# Generated by Django 6.0.2 on 2026-03-02 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_candidatura_lgpd_consentimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_solicitante', models.CharField(max_length=100, verbose_name='Seu Cargo Atual')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('COMPRAS', 'Compras'), ('DIRETORIA', 'Diretoria'), ('FINANCEIRO', 'Financeiro'), ('OBRA', 'Obra'), ('ORCAMENTO', 'Orçamento'), ('QUALIDADE', 'Planejamento Processo e Qualidade'), ('PRODUCAO', 'Produção'), ('PROJETOS', 'Projetos'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=50)),
                ('nome_vaga', models.CharField(max_length=150, verbose_name='Nome da Vaga')),
                ('quantidade_vagas', models.PositiveIntegerField(default=1)),
                ('data_prevista_inicio', models.DateField(verbose_name='Data Prevista para Início')),
                ('motivo', models.CharField(choices=[('AUMENTO_FUNC', 'Aumento de quadro - Funcionário'), ('AUMENTO_ESTAG', 'Aumento de quadro - Estagiário'), ('SUBST_DEMITIDO', 'Substituição - Demitido'), ('SUBST_PEDIDO', 'Substituição - Pedido de demissão'), ('TEMP_AFASTAMENTO', 'Temporário - Afastamento')], max_length=20)),
                ('nome_substituido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Substituído (Se houver)')),
                ('descricao_atividades', models.TextField(verbose_name='Descrição Sumária das Atividades')),
                ('sexo', models.CharField(choices=[('INDIFERENTE', 'Indiferente / Qualquer'), ('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='INDIFERENTE', max_length=15)),
                ('escolaridade', models.CharField(choices=[('FUNDAMENTAL', 'Ensino Fundamental Completo'), ('MEDIO', 'Ensino Médio Completo'), ('TECNICO', 'Curso Técnico'), ('SUP_CURSANDO', 'Superior Cursando'), ('SUP_COMPLETO', 'Superior Completo')], max_length=20)),
                ('curso_area', models.CharField(blank=True, max_length=150, null=True, verbose_name='Curso e/ou Área')),
                ('conhecimentos_desejaveis', models.TextField(verbose_name='Conhecimentos e/ou experiências')),
                ('atitudes_desejaveis', models.TextField(verbose_name='Atitudes desejáveis')),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação do RH'), ('APROVADA', 'Aprovada (Vaga Aberta)'), ('REPROVADA', 'Reprovada / Cancelada')], default='PENDENTE', max_length=20)),
                ('observacoes_rh', models.TextField(blank=True, null=True, verbose_name='Parecer do RH')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_vagas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
