# Generated by Django 6.0.2 on 2026-03-03 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_solicitacaovaga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='solicitacao_origem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaga_gerada', to='rh.solicitacaovaga'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='rh.vaga'),
        ),
        migrations.CreateModel(
            name='PesquisaDemissional',
            fields=[
                ('id_pesquisa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('respondida', models.BooleanField(default=False, verbose_name='Pesquisa já foi respondida?')),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('ex_funcionario_nome', models.CharField(max_length=150, verbose_name='Nome do Ex-Colaborador')),
                ('setor', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('COMPRAS', 'Compras'), ('DIRETORIA', 'Diretoria'), ('FINANCEIRO', 'Financeiro'), ('OBRA', 'Obra'), ('ORCAMENTO', 'Orçamento'), ('QUALIDADE', 'Planejamento Processo e Qualidade'), ('PRODUCAO', 'Produção'), ('PROJETOS', 'Projetos'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=50)),
                ('tipo_demissao', models.CharField(choices=[('VOLUNTARIA', 'Pedido de Demissão (Iniciativa do Colaborador)'), ('INVOLUNTARIA', 'Demissão sem Justa Causa (Iniciativa da Empresa)'), ('JUSTA_CAUSA', 'Demissão por Justa Causa'), ('ACORDO', 'Acordo entre as partes')], max_length=50)),
                ('periodo_saida', models.CharField(max_length=50, verbose_name='Mês/Ano de Saída')),
                ('tempo_casa', models.CharField(max_length=50, verbose_name='Tempo de Casa')),
                ('motivo_saida', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo Principal da Saída')),
                ('diferente', models.TextField(blank=True, null=True, verbose_name='O que poderia ter sido feito diferente?')),
                ('nota_lideranca', models.IntegerField(blank=True, null=True, verbose_name='Nota - Liderança')),
                ('nota_oportunidade', models.IntegerField(blank=True, null=True, verbose_name='Nota - Oportunidades')),
                ('nota_reconhecimento', models.IntegerField(blank=True, null=True, verbose_name='Nota - Reconhecimento')),
                ('nota_clima', models.IntegerField(blank=True, null=True, verbose_name='Nota - Clima Organizacional')),
                ('nota_recomendacao', models.IntegerField(blank=True, null=True, verbose_name='Nota - Recomendação da Empresa (eNPS)')),
                ('gerada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_geradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
