# Generated by Django 6.0.2 on 2026-04-15 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_alter_candidatura_status_alter_vaga_setor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisademissional',
            name='setor',
            field=models.CharField(choices=[('CA', 'Comercial'), ('CO', 'Compras'), ('DI', 'Diretoria'), ('FI', 'Financeiro'), ('OB', 'Obra'), ('QA', 'SGQ'), ('FA', 'Fabrica'), ('PR', 'Projetos'), ('EG', 'Engenharia'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitacaovaga',
            name='departamento',
            field=models.CharField(choices=[('CA', 'Comercial'), ('CO', 'Compras'), ('DI', 'Diretoria'), ('FI', 'Financeiro'), ('OB', 'Obra'), ('QA', 'SGQ'), ('FA', 'Fabrica'), ('PR', 'Projetos'), ('EG', 'Engenharia'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=2),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacao', models.CharField(choices=[('AT', 'Trabalhando'), ('DE', 'Desligado'), ('AF', 'Afastado')], default='AT', max_length=2)),
                ('setor', models.CharField(choices=[('CA', 'Comercial'), ('CO', 'Compras'), ('DI', 'Diretoria'), ('FI', 'Financeiro'), ('OB', 'Obra'), ('QA', 'SGQ'), ('FA', 'Fabrica'), ('PR', 'Projetos'), ('EG', 'Engenharia'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
