# Generated by Django 6.0.2 on 2026-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_alter_pesquisademissional_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='situacao',
            field=models.CharField(choices=[('AT', 'Trabalhando'), ('DM', 'Demitido')], default='AT', max_length=2),
        ),
    ]
