# Generated by Django 6.0.2 on 2026-04-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_alter_funcionario_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RegistroAbsenteirmos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('horas_normais', models.DurationField(blank=True, null=True)),
                ('horas_falta', models.DurationField(blank=True, null=True)),
                ('horas_extras', models.DurationField(blank=True, null=True)),
                ('abono', models.DurationField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='rh.funcionario')),
            ],
            options={
                'unique_together': {('funcionario', 'data_referencia')},
            },
        ),
    ]
