# Generated by Django 6.0.2 on 2026-04-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_funcionario_matricula_registroabsenteirmos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroAbsenteirmos',
            new_name='RegistroAbsenteismo',
        ),
    ]
