# Generated by Django 4.2.30 on 2026-06-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0010_rename_registroabsenteirmos_registroabsenteismo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioAdmissional',
            fields=[
                ('id_formulario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False, verbose_name='Formulario ja foi respondido?')),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('candidato_nome_interno', models.CharField(max_length=150, verbose_name='Nome completo do futuro colaborador')),
                ('observacoes_rh', models.TextField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cidade_estado', models.CharField(blank=True, help_text='Ex.: Araucaria-PR', max_length=120, null=True)),
                ('pis', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_ctps', models.CharField(blank=True, max_length=30, null=True)),
                ('serie_ctps', models.CharField(blank=True, max_length=30, null=True)),
                ('uf_ctps', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True)),
                ('cep', models.CharField(blank=True, help_text='Ex.: 00000000', max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, help_text='Rua, Numero, Bairro e Complemento', max_length=255, null=True)),
                ('telefone_principal', models.CharField(blank=True, help_text='Ex.: DD 99999-9999', max_length=20, null=True)),
                ('contato_recado', models.CharField(blank=True, help_text='Ex.: DD 99999-9999', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_nascimento', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True)),
                ('naturalidade', models.CharField(blank=True, help_text='Cidade onde nasceu', max_length=120, null=True)),
                ('cor_raca', models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indigena'), ('NAO_INFORMAR', 'Prefiro nao informar')], max_length=20, null=True)),
                ('grau_instrucao', models.CharField(blank=True, choices=[('FUND_INCOMPLETO', 'Ensino Fundamental Incompleto'), ('FUND_COMPLETO', 'Ensino Fundamental Completo'), ('MEDIO_INCOMPLETO', 'Ensino Medio Incompleto'), ('MEDIO_COMPLETO', 'Ensino Medio Completo'), ('SUPERIOR_INCOMPLETO', 'Ensino Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior Completo'), ('POS_GRADUACAO', 'Pos-graduacao'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=30, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_rg', models.CharField(blank=True, max_length=30, null=True)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=30, null=True)),
                ('uf_rg', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True)),
                ('data_emissao_rg', models.DateField(blank=True, null=True)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=30, null=True)),
                ('zona_eleitoral', models.CharField(blank=True, max_length=20, null=True)),
                ('secao_eleitoral', models.CharField(blank=True, max_length=20, null=True)),
                ('uf_titulo_eleitor', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True)),
                ('reservista', models.CharField(blank=True, max_length=50, null=True)),
                ('cnh', models.CharField(blank=True, help_text='Informar numero, validade e estado', max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('UNIAO_ESTAVEL', 'Uniao Estavel'), ('DIVORCIADO', 'Divorciado(a)'), ('SEPARADO', 'Separado(a)'), ('VIUVO', 'Viuvo(a)')], max_length=20, null=True)),
                ('possui_dependentes_ir', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Nao')], max_length=3, null=True)),
                ('botina', models.CharField(blank=True, choices=[('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=2, null=True)),
                ('camisa', models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XXG', 'XXG')], max_length=3, null=True)),
                ('calca', models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XXG', 'XXG'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54')], max_length=3, null=True)),
                ('utiliza_vale_transporte', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Nao')], max_length=3, null=True)),
                ('lgpd_consentimento', models.BooleanField(default=False)),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios_admissionais_gerados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DependenteAdmissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14)),
                ('cidade_estado_nascimento', models.CharField(max_length=120)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='rh.formularioadmissional')),
            ],
        ),
    ]
