# Generated by Django 4.2.30 on 2026-06-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_formularioadmissional_dependenteadmissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioadmissional',
            name='funcao_pretendida',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formularioadmissional',
            name='trajeto_vale_transporte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
