# Generated by Django 4.2.30 on 2026-06-08 13:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_formularioadmissional_funcao_pretendida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioadmissional',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='formularioadmissional',
            name='estado_cnh',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='formularioadmissional',
            name='numero_cnh',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='formularioadmissional',
            name='validade_cnh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='contato_recado',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ex.: DD 99999-9999', max_length=128, null=True, region='BR'),
        ),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='endereco',
            field=models.CharField(blank=True, help_text='Rua e numero', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='naturalidade',
            field=models.CharField(blank=True, choices=[('Araucaria-PR', 'Araucária-PR'), ('Curitiba-PR', 'Curitiba-PR'), ('Sao Jose dos Pinhais-PR', 'São José dos Pinhais-PR'), ('Colombo-PR', 'Colombo-PR'), ('Pinhais-PR', 'Pinhais-PR'), ('Campo Largo-PR', 'Campo Largo-PR'), ('Fazenda Rio Grande-PR', 'Fazenda Rio Grande-PR'), ('Ponta Grossa-PR', 'Ponta Grossa-PR'), ('Londrina-PR', 'Londrina-PR'), ('Maringa-PR', 'Maringá-PR'), ('Cascavel-PR', 'Cascavel-PR'), ('Foz do Iguacu-PR', 'Foz do Iguaçu-PR'), ('Florianopolis-SC', 'Florianópolis-SC'), ('Joinville-SC', 'Joinville-SC'), ('Blumenau-SC', 'Blumenau-SC'), ('Porto Alegre-RS', 'Porto Alegre-RS'), ('Sao Paulo-SP', 'São Paulo-SP'), ('Rio de Janeiro-RJ', 'Rio de Janeiro-RJ'), ('Belo Horizonte-MG', 'Belo Horizonte-MG'), ('Brasilia-DF', 'Brasília-DF'), ('Salvador-BA', 'Salvador-BA'), ('Fortaleza-CE', 'Fortaleza-CE'), ('Recife-PE', 'Recife-PE'), ('Manaus-AM', 'Manaus-AM'), ('Belem-PA', 'Belém-PA'), ('Goiania-GO', 'Goiânia-GO'), ('Cuiaba-MT', 'Cuiabá-MT'), ('Campo Grande-MS', 'Campo Grande-MS'), ('Vitoria-ES', 'Vitória-ES')], help_text='Cidade onde nasceu', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='orgao_expedidor',
            field=models.CharField(blank=True, choices=[('SSP', 'SSP - Secretaria de Segurança Pública'), ('SESP', 'SESP - Secretaria de Estado de Segurança Pública'), ('SESPAP', 'SESPAP - Secretaria de Estado de Segurança Pública e Administração Penitenciária'), ('GEJSPC', 'GEJSPC - Gerência de Estado de Justiça, Segurança Pública e Cidadania'), ('PC', 'PC - Polícia Civil'), ('PCMG', 'PCMG - Polícia Civil do Estado de Minas Gerais'), ('PCEMG', 'PCEMG - Polícia Civil do Estado de Minas Gerais'), ('SSPPC', 'SSPPC - SSP / Polícia Civil'), ('DETRAN', 'DETRAN - Departamento Estadual de Trânsito'), ('DPF', 'DPF - Departamento de Polícia Federal'), ('SEJUSP', 'SEJUSP - Secretaria de Estado de Justiça e Segurança Pública'), ('SEJSP', 'SEJSP - Secretaria de Estado de Justiça e Segurança Pública'), ('SGPC', 'SGPC - Superintendência Geral de Polícia Civil'), ('CPP', 'CPP - Centro de Perícias do Paraná'), ('SDS', 'SDS - Secretaria de Defesa Social'), ('SECC', 'SECC - Secretaria de Estado da Casa Civil'), ('DGPC', 'DGPC - Diretoria Geral da Polícia Civil'), ('SEJUSO', 'SEJUSO - Secretaria de Estado de Justiça e Segurança Pública'), ('SJS', 'SJS - Secretaria da Justiça e Segurança'), ('SJTC', 'SJTC - Secretaria da Justiça do Trabalho e Cidadania'), ('SJTS', 'SJTS - Secretaria da Justiça do Trabalho e Segurança'), ('SPTC', 'SPTC - Secretaria de Polícia Técnico-Científica'), ('MTE', 'MTE - Ministério do Trabalho e Emprego'), ('MMA', 'MMA - Ministério da Marinha'), ('MEX', 'MEX - Ministério do Exército'), ('MAE', 'MAE - Ministério da Aeronáutica'), ('SESDC', 'SESDC - Secretaria de Estado da Segurança, Defesa e Cidadania')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='serie_ctps',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='telefone_principal',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ex.: DD 99999-9999', max_length=128, null=True, region='BR'),
        ),
    ]
