# Generated by Django 4.2.30 on 2026-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_formularioadmissional_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioadmissional',
            name='naturalidade',
            field=models.CharField(blank=True, help_text='Cidade onde nasceu', max_length=120, null=True),
        ),
    ]
