# Generated by Django 4.2.30 on 2026-06-09 11:05

import re

from django.db import migrations, models
import phonenumber_field.modelfields


def normalizar_numeros_ctps(apps, schema_editor):
    FormularioAdmissional = apps.get_model('rh', 'FormularioAdmissional')

    formularios = FormularioAdmissional.objects.exclude(numero_ctps__isnull=True).exclude(numero_ctps='')
    for formulario in formularios.iterator():
        numero_ctps = re.sub(r'\D', '', formulario.numero_ctps or '')
        formulario.numero_ctps = numero_ctps if len(numero_ctps) <= 11 else None
        formulario.save(update_fields=['numero_ctps'])


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_alter_formularioadmissional_naturalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependenteadmissional',
            name='grau_parentesco',
            field=models.CharField(blank=True, choices=[('FILHO', 'Filho(a)'), ('ENTEADO', 'Enteado(a)'), ('CONJUGE', 'Cônjuge'), ('COMPANHEIRO', 'Companheiro(a)'), ('PAI', 'Pai'), ('MAE', 'Mãe'), ('IRMAO', 'Irmão(ã)'), ('NETO', 'Neto(a)'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Grau de parentesco'),
        ),
        migrations.AddField(
            model_name='formularioadmissional',
            name='grau_parentesco_contato_recado',
            field=models.CharField(blank=True, choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('FILHO', 'Filho(a)'), ('IRMAO', 'Irmão(ã)'), ('CONJUGE', 'Cônjuge'), ('COMPANHEIRO', 'Companheiro(a)'), ('AVO', 'Avô/Avó'), ('TIO', 'Tio(a)'), ('PRIMO', 'Primo(a)'), ('AMIGO', 'Amigo(a)'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Grau de parentesco'),
        ),
        migrations.AddField(
            model_name='formularioadmissional',
            name='nome_contato_recado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do contato para recado'),
        ),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='contato_recado',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ex.: DD 99999-9999', max_length=128, null=True, region='BR', verbose_name='Telefone para recado'),
        ),
        migrations.RunPython(normalizar_numeros_ctps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='formularioadmissional',
            name='numero_ctps',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Número da CTPS'),
        ),
    ]
