# Generated by Django 4.2.30 on 2026-06-08 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0015_dependenteadmissional_grau_parentesco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('ciclo', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('mes_referencia', models.CharField(max_length=20)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('avaliada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_desempenho_realizadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_desempenho', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Avaliacao de desempenho',
                'verbose_name_plural': 'Avaliacoes de desempenho',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('funcionario', 'ano', 'ciclo')},
            },
        ),
        migrations.CreateModel(
            name='CompetenciaDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Competencia de desempenho',
                'verbose_name_plural': 'Competencias de desempenho',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='NotaCompetenciaDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='rh.avaliacaodesempenho')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_desempenho', to='rh.competenciadesempenho')),
            ],
            options={
                'verbose_name': 'Nota de competencia de desempenho',
                'verbose_name_plural': 'Notas de competencias de desempenho',
                'ordering': ['competencia__ordem', 'competencia__nome'],
                'unique_together': {('avaliacao', 'competencia')},
            },
        ),
    ]
