# Generated by Django 4.2.30 on 2026-06-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_competencias_desempenho_iniciais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaodesempenho',
            name='mes_referencia',
        ),
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='ciclo',
            field=models.CharField(choices=[('A', 'A - Junho'), ('B', 'B - Dezembro')], max_length=1),
        ),
    ]
