# Generated by Django 4.2.30 on 2026-06-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0018_remove_avaliacaodesempenho_mes_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_desempenho', to=settings.AUTH_USER_MODEL),
        ),
    ]
