# Generated by Django 6.0.2 on 2026-03-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_compras',
            field=models.BooleanField(default=False, verbose_name='Acesso Compras'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pcp',
            field=models.BooleanField(default=False, verbose_name='Acesso PCP'),
        ),
    ]
