# Generated by Django 4.2.30 on 2026-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_is_qualidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rdo',
            field=models.BooleanField(default=False, verbose_name='Acesso Rdo'),
        ),
    ]
