# Generated by Django 5.0.4 on 2024-07-16 13:35

from django.db import migrations

def create_groups_and_assign_users(apps, schema_editor):
    """
    Cria os grupos baseados nos campos booleanos existentes no CustomUser
    e associa os usuários a esses grupos.
    """
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('usuarios', 'CustomUser')

    # Mapeamento de campos booleanos para nomes de grupos
    GROUP_MAPPING = {
        'is_comercial': 'Comercial',
        'is_ti': 'TI',
        'is_financeiro': 'Financeiro',
        'is_rh': 'RH',
        'is_engenharia': 'Engenharia',
        'is_diretoria': 'Diretoria',
        'is_compras': 'Compras',
        'is_pcp': 'PCP',
        'is_qualidade': 'Qualidade',
        'is_rdo': 'RDO',
    }

    # 1. Criar os grupos
    for group_name in GROUP_MAPPING.values():
        Group.objects.get_or_create(name=group_name)

    # 2. Associar usuários aos grupos
    for user in User.objects.all():
        for field, group_name in GROUP_MAPPING.items():
            if getattr(user, field, False):
                group = Group.objects.get(name=group_name)
                user.groups.add(group)

def remove_groups(apps, schema_editor):
    """
    Remove os grupos criados. Função de rollback.
    """
    Group = apps.get_model('auth', 'Group')
    
    GROUP_NAMES = [
        'Comercial', 'TI', 'Financeiro', 'RH', 'Engenharia', 
        'Diretoria', 'Compras', 'PCP', 'Qualidade', 'RDO'
    ]

    Group.objects.filter(name__in=GROUP_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_customuser_is_rdo'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_assign_users, remove_groups),
    ]
