# Generated by Django 4.2.30 on 2026-06-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_create_groups_and_assign_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_comercial',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_compras',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_diretoria',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_engenharia',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_financeiro',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_pcp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_qualidade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_rdo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_rh',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_ti',
        ),
    ]
