# Generated by Django 6.0.2 on 2026-05-11 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_inicial', models.TimeField(verbose_name='Horário inicial')),
                ('horario_final', models.TimeField(verbose_name='Horário final')),
                ('descricao', models.TextField(verbose_name='Descrição / Motivo')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_sala', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Reserva de Sala',
                'verbose_name_plural': 'Reservas de Sala',
                'ordering': ['-data', 'horario_inicial'],
            },
        ),
    ]
