# Generated by Django 6.0.2 on 2026-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_sala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasala',
            name='recorrencia_semanal_weeks',
            field=models.PositiveIntegerField(default=12, help_text='Quantidade de semanas para repetir (inclui a semana atual)', verbose_name='Nº de semanas (inclui esta)'),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='recorrente_semanal',
            field=models.BooleanField(default=False, verbose_name='Repetir toda semana'),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='serie',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
