"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import mimetypes
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from celery.schedules import crontab
from django.conf.global_settings import USE_THOUSAND_SEPARATOR, EMAIL_HOST_PASSWORD
from dotenv import load_dotenv
import ssl


load_dotenv()

mimetypes.add_type('text/css', '.css', True)

BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = ['iNoveTmg.pythonanywhere.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'phonenumber_field',
    'core',
    'usuarios',
    'ti',
    'comercial',
    'rh',
    'compras',
    'financeiro',
    'engenharia',
    'pcp',
    'qualidade',
    'reserva_sala',
    'rdo',
    'rest_framework'
]

AUTH_USER_MODEL = 'usuarios.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.permissoes_avaliacao_desempenho',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PCP_PRIVATE_MEDIA_ROOT = Path(os.getenv('PCP_PRIVATE_MEDIA_ROOT', str(BASE_DIR / 'private_media' / 'pcp')))
PCP_MAX_EVIDENCE_FILES = int(os.getenv('PCP_MAX_EVIDENCE_FILES', '10'))
PCP_MAX_EVIDENCE_SIZE = int(os.getenv('PCP_MAX_EVIDENCE_SIZE', str(10 * 1024 * 1024)))
PCP_MAINTENANCE_ALERT_RECIPIENTS = [
    item.strip().lower()
    for item in os.getenv('PCP_MAINTENANCE_ALERT_RECIPIENTS', '').replace(';', ',').split(',')
    if item.strip()
]


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'inovetmgti@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', str(60 * 60 * 24)))


WIDGET_ERROR_CLASS = 'is-invalid'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PHONENUMBER_DEFAULT_REGION = 'BR'
PHONENUMBER_DB_FORMAT = 'E164'


# --- CONFIGURAÇÕES DO CELERY E REDIS ---

CELERY_REDIS_VISIBILITY_TIMEOUT = int(os.getenv('CELERY_REDIS_VISIBILITY_TIMEOUT', str(60 * 60)))
CELERY_REDIS_MAX_CONNECTIONS = int(os.getenv('CELERY_REDIS_MAX_CONNECTIONS', '10'))
CELERY_REDIS_SOCKET_TIMEOUT = int(os.getenv('CELERY_REDIS_SOCKET_TIMEOUT', '60'))
CELERY_REDIS_SOCKET_CONNECT_TIMEOUT = int(os.getenv('CELERY_REDIS_SOCKET_CONNECT_TIMEOUT', '60'))
CELERY_REDIS_HEALTH_CHECK_INTERVAL = int(os.getenv('CELERY_REDIS_HEALTH_CHECK_INTERVAL', '30'))


def _celery_redis_ssl_cert_reqs_name():
    cert_reqs = os.getenv('CELERY_REDIS_SSL_CERT_REQS', 'required').strip().lower()
    options = {
        'required': 'required',
        'cert_required': 'required',
        'none': 'none',
        'cert_none': 'none',
        'optional': 'optional',
        'cert_optional': 'optional',
    }
    return options.get(cert_reqs, 'required')


def _celery_redis_ssl_cert_reqs():
    options = {
        'required': ssl.CERT_REQUIRED,
        'none': ssl.CERT_NONE,
        'optional': ssl.CERT_OPTIONAL,
    }
    return options[_celery_redis_ssl_cert_reqs_name()]


def _normalize_celery_redis_url(url):
    if not url:
        return url

    if url.startswith('redis://'):
        url = 'rediss://' + url[len('redis://'):]

    if not url.startswith('rediss://'):
        return url

    parts = urlsplit(url)
    query = dict(parse_qsl(parts.query, keep_blank_values=True))
    query.setdefault('ssl_cert_reqs', _celery_redis_ssl_cert_reqs_name())
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment))


if DEBUG:
    # AMBIENTE LOCAL (DESENVOLVIMENTO)
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_TASK_STORE_EAGER_RESULT = True
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'
else:
    # AMBIENTE PRODUÇÃO (PYTHONANYWHERE + UPSTASH)
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_BROKER_URL = _normalize_celery_redis_url(os.getenv('CELERY_BROKER_URL'))
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL

    # Configurações de SSL para Upstash (Corrigido)
    CELERY_REDIS_SSL = {'ssl_cert_reqs': _celery_redis_ssl_cert_reqs()}
    CELERY_BROKER_USE_SSL = CELERY_REDIS_SSL
    CELERY_REDIS_BACKEND_USE_SSL = CELERY_REDIS_SSL

    # Otimização de Conexão para PythonAnywhere
    CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
    CELERY_TASK_PUBLISH_RETRY = True
    CELERY_TASK_PUBLISH_RETRY_POLICY = {
        'max_retries': 5,
        'interval_start': 0,
        'interval_step': 0.5,
        'interval_max': 3,
    }

    # Limite de conexões (Upstash Free suporta poucas conexões simultâneas)
    CELERY_BROKER_POOL_LIMIT = CELERY_REDIS_MAX_CONNECTIONS

    # Estabilidade da conexão
    CELERY_BROKER_HEARTBEAT = None
    CELERY_BROKER_TRANSPORT_OPTIONS = {
        'visibility_timeout': CELERY_REDIS_VISIBILITY_TIMEOUT,
        'max_connections': CELERY_REDIS_MAX_CONNECTIONS,
        'socket_timeout': CELERY_REDIS_SOCKET_TIMEOUT,
        'socket_connect_timeout': CELERY_REDIS_SOCKET_CONNECT_TIMEOUT,
        'socket_keepalive': True,
        'health_check_interval': CELERY_REDIS_HEALTH_CHECK_INTERVAL,
        'retry_on_timeout': True,
    }
    CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
        'visibility_timeout': CELERY_REDIS_VISIBILITY_TIMEOUT,
    }
    CELERY_VISIBILITY_TIMEOUT = CELERY_REDIS_VISIBILITY_TIMEOUT
    CELERY_REDIS_SOCKET_KEEPALIVE = True
    CELERY_REDIS_RETRY_ON_TIMEOUT = True

# Configurações globais
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_RESULT_EXPIRES = 3600
CELERY_BEAT_SCHEDULE = {
    'ti-fechar-chamados-resolvidos-sem-feedback': {
        'task': 'ti.tasks.task_fechar_chamados_resolvidos_sem_feedback',
        'schedule': crontab(hour=1, minute=0),
    },
    'pcp-recalcular-preventivas': {
        'task': 'pcp.recalcular_preventivas',
        'schedule': crontab(hour=5, minute=0),
    },
    'pcp-enviar-alertas-preventivas': {
        'task': 'pcp.enviar_alertas_preventivas',
        'schedule': crontab(hour=7, minute=0),
    },
    'pcp-enviar-alertas-downtime-aberto': {
        'task': 'pcp.enviar_alertas_downtime_aberto',
        'schedule': crontab(minute=0),
    },
}


# --- Integracoes externas ---
POWER_AUTOMATE_USER_WEBHOOK_URL = os.getenv('TEAMS_WEBHOOK_URL')
TEAMS_TI_WEBHOOK_URL = os.getenv('TEAMS_TI_WEBHOOK_URL')
POWER_BI_API_KEY = os.getenv('POWER_BI_API_KEY', '')


# --- Politica de anexos do modulo TI ---
TI_MAX_UPLOAD_FILES = int(os.getenv('TI_MAX_UPLOAD_FILES', '5'))
TI_MAX_UPLOAD_SIZE = int(os.getenv('TI_MAX_UPLOAD_SIZE', str(5 * 1024 * 1024)))
TI_ALLOWED_UPLOAD_CONTENT_TYPES = {
    item.strip()
    for item in os.getenv('TI_ALLOWED_UPLOAD_CONTENT_TYPES', 'image/jpeg,image/png,image/webp').split(',')
    if item.strip()
}
