# Generated by Django 6.0.2 on 2026-02-27 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware (computadores, notebooks, impressoras, periféricos)'), ('SOFTWARE_BASICO', 'Software Básico (sistema operacional, drivers, office)'), ('SOFTWARE_CORPORATIVO', 'Sistemas Corporativos (ERP, PROTHEUS, CRM, BI)'), ('REDE', 'Rede e Conectividade (internet, VPN, switches, roteadores)'), ('ACESSO', 'Gestão de Acessos (criação/remoção de usuários, senhas, permissões)'), ('SEGURANCA', 'Segurança da Informação (antivírus, firewall, incidentes, backup)'), ('INFRAESTRUTURA', 'Infraestrutura (servidores, storage, virtualização, backups)'), ('BANCO_DADOS', 'Banco de Dados (manutenção, performance, consultas)'), ('TELEFONIA', 'Telefonia / VoIP (ramais, softphones, centrais)'), ('EMAIL', 'Correio Eletrônico e Colaboração (e-mail, calendário, Teams, Slack)'), ('DESENVOLVIMENTO', 'Desenvolvimento (criação de apps, sites, sistemas, automações)'), ('MOBILIDADE', 'Dispositivos Móveis (celulares, tablets, configuração de e-mail)'), ('NUVEM', 'Serviços em Nuvem (AWS, Azure, Google Workspace, Dropbox)'), ('IMPRESSAO', 'Impressão e Digitalização (configuração, manutenção, filas)'), ('TREINAMENTO', 'Treinamento e Orientação (uso de sistemas, boas práticas)'), ('OUTROS', 'Outros (demandas não classificadas nas categorias anteriores)')], default='OUTROS', max_length=30)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa - Impacto mínimo, sem interrupção'), ('MEDIA', 'Média - Impacto localizado, mas não impede o trabalho'), ('ALTA', 'Alta - Setor ou processo parcialmente interrompido'), ('CRITICA', 'Crítica - Operação da empresa interrompida (atendimento imediato)')], default='BAIXA', max_length=20)),
                ('setor', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('COMPRAS', 'Compras'), ('DIRETORIA', 'Diretoria'), ('FINANCEIRO', 'Financeiro'), ('OBRA', 'Obra'), ('ORCAMENTO', 'Orçamento'), ('PLANETAMENTO PROCESSO E QUALIDADE', 'Planejamento Processo e Qualidade'), ('PRODUCAO', 'Produção'), ('PROJETOS', 'Projetos'), ('RECURSOS HUMADOS', 'Recursos Humados'), ('T.I', 'T.I')], default='T.I', max_length=50)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo (aguardando triagem)'), ('ATRIBUIDO', 'Atribuído para análise'), ('EM_ANALISE', 'Em análise técnica'), ('EM_ATENDIMENTO', 'Em atendimento / execução'), ('AGUARDANDO_USUARIO', 'Aguardando resposta'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação (gestor/área responsável)'), ('AGUARDANDO_TERCEIRO', 'Aguardando fornecedor / peça / suporte externo'), ('RESOLVIDO', 'Resolvido (aguardando validação do usuário)'), ('CONCLUIDO', 'Concluído (validado pelo usuário)'), ('CANCELADO', 'Cancelado (solicitante desistiu ou chamado duplicado)')], default='NOVO', max_length=25)),
                ('solucao', models.TextField(blank=True, verbose_name='Solução Utilizada')),
                ('validado_pelo_solicitante', models.BooleanField(default=False, help_text='Indica se o usuário testou e confirmou a resolução do problema.', verbose_name='Validado pelo Solicitante')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='ChamadoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='chamados/%Y/%m/')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ti.chamado')),
            ],
        ),
    ]
