# Generated by Django 6.0.2 on 2026-04-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0002_alter_chamado_categoria_alter_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.CharField(choices=[('COMERCIAL', 'Comercial'), ('COMPRAS', 'Compras'), ('DIRETORIA', 'Diretoria'), ('FINANCEIRO', 'Financeiro'), ('OBRA', 'Obra'), ('ORCAMENTO', 'Orçamento'), ('SGQ', 'SGQ'), ('PRODUCAO', 'Produção'), ('PROJETOS', 'Projetos'), ('RECURSOS HUMADOS', 'Recursos Humados'), ('T.I', 'T.I')], default='', max_length=50),
        ),
    ]
