# Generated by Django 4.2.30 on 2026-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0003_alter_chamado_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('HARDWARE', 'Hardware (computadores, notebooks, impressoras, periféricos)'), ('SOFTWARE_BASICO', 'Software Básico (sistema operacional, drivers, office)'), ('SOFTWARE_CORPORATIVO', 'Sistemas Corporativos (ERP, PROTHEUS, CRM, BI)'), ('REDE', 'Rede e Conectividade (internet, VPN, switches, roteadores)'), ('ACESSO', 'Gestão de Acessos (criação/remoção de usuários, senhas, permissões)'), ('SEGURANCA', 'Segurança da Informação (antivírus, firewall, incidentes, backup)'), ('INFRAESTRUTURA', 'Servidores, storage, virtualização, backups'), ('BANCO_DADOS', 'Banco de Dados (manutenção, performance, consultas)'), ('TELEFONIA', 'Telefonia / VoIP (ramais, softphones, centrais)'), ('EMAIL', 'Correio Eletrônico e Colaboração (e-mail, calendário, Teams, Slack)'), ('DESENVOLVIMENTO', 'Desenvolvimento (criação de apps, sites, sistemas, automações)'), ('MOBILIDADE', 'Dispositivos Móveis (celulares, tablets, configuração de e-mail)'), ('NUVEM', 'Serviços em Nuvem (AWS, Azure, Google Workspace, Dropbox)'), ('IMPRESSAO', 'Impressão e Digitalização (configuração, manutenção, filas)'), ('TREINAMENTO', 'Treinamento e Orientação (uso de sistemas, boas práticas)'), ('OUTROS', 'Outros (demandas não classificadas nas categorias anteriores)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='validado_pelo_solicitante',
            field=models.BooleanField(default=False),
        ),
    ]
