# Generated by Django 4.2.30 on 2026-05-18 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ti', '0004_alter_chamado_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('HARDWARE', 'Hardware (computadores, notebooks, impressoras, perifericos)'), ('SOFTWARE_BASICO', 'Software Basico (sistema operacional, drivers, office)'), ('SOFTWARE_CORPORATIVO', 'Sistemas Corporativos (ERP, PROTHEUS, CRM, BI)'), ('REDE', 'Rede e Conectividade (internet, VPN, switches, roteadores)'), ('ACESSO', 'Gestao de Acessos (criacao/remocao de usuarios, senhas, permissoes)'), ('SEGURANCA', 'Seguranca da Informacao (antivirus, firewall, incidentes, backup)'), ('INFRAESTRUTURA', 'Servidores, storage, virtualizacao, backups'), ('BANCO_DADOS', 'Banco de Dados (manutencao, performance, consultas)'), ('TELEFONIA', 'Telefonia / VoIP (ramais, softphones, centrais)'), ('EMAIL', 'Correio Eletronico e Colaboracao (e-mail, calendario, Teams, Slack)'), ('DESENVOLVIMENTO', 'Desenvolvimento (criacao de apps, sites, sistemas, automacoes)'), ('MOBILIDADE', 'Dispositivos Moveis (celulares, tablets, configuracao de e-mail)'), ('NUVEM', 'Servicos em Nuvem (AWS, Azure, Google Workspace, Dropbox)'), ('IMPRESSAO', 'Impressao e Digitalizacao (configuracao, manutencao, filas)'), ('TREINAMENTO', 'Treinamento e Orientacao (uso de sistemas, boas praticas)'), ('OUTROS', 'Outros (demandas nao classificadas nas categorias anteriores)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(verbose_name='Descricao do Problema'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa - Impacto minimo, sem interrupcao'), ('MEDIA', 'Media - Impacto localizado, mas nao impede o trabalho'), ('ALTA', 'Alta - Setor ou processo parcialmente interrompido'), ('CRITICA', 'Critica - Operacao da empresa interrompida (atendimento imediato)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.CharField(choices=[('COMERCIAL', 'Comercial'), ('COMPRAS', 'Compras'), ('DIRETORIA', 'Diretoria'), ('FINANCEIRO', 'Financeiro'), ('OBRA', 'Obra'), ('ORCAMENTO', 'Orcamento'), ('SGQ', 'SGQ'), ('PRODUCAO', 'Producao'), ('PROJETOS', 'Projetos'), ('RECURSOS HUMANOS', 'Recursos Humanos'), ('T.I', 'T.I')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solucao',
            field=models.TextField(blank=True, verbose_name='Solucao Utilizada'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo (aguardando triagem)'), ('ATRIBUIDO', 'Atribuido para analise'), ('EM_ANALISE', 'Em analise tecnica'), ('EM_ATENDIMENTO', 'Em atendimento / execucao'), ('AGUARDANDO_USUARIO', 'Aguardando resposta'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovacao (gestor/area responsavel)'), ('AGUARDANDO_TERCEIRO', 'Aguardando fornecedor / peca / suporte externo'), ('RESOLVIDO', 'Resolvido (aguardando validacao do usuario)'), ('CONCLUIDO', 'Concluido (validado pelo usuario)'), ('CANCELADO', 'Cancelado (solicitante desistiu ou chamado duplicado)')], default='NOVO', max_length=25),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico Responsavel'),
        ),
    ]
