# Generated by Django 4.2.30 on 2026-05-19 13:00

from django.db import migrations, models
from django.utils import timezone


def iniciar_janela_feedback_chamados_resolvidos(apps, schema_editor):
    Chamado = apps.get_model('ti', 'Chamado')
    Chamado.objects.filter(status='RESOLVIDO', data_resolucao__isnull=True).update(
        data_resolucao=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0006_normalize_recursos_humanos_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_resolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='encerrado_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(iniciar_janela_feedback_chamados_resolvidos, migrations.RunPython.noop),
    ]
