# Generated by Django 4.2.30 on 2026-05-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0007_chamado_data_resolucao_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['status', 'validado_pelo_solicitante', 'encerrado_automaticamente', 'data_resolucao'], name='ti_chamado_auto_close_idx'),
        ),
    ]
