# Generated by Django 6.0.2 on 2026-02-26 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=150, verbose_name='Contato (Nome/Telefone)')),
                ('atividade', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da STO')),
                ('data', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('orc_obras', models.BooleanField(default=False, verbose_name='Obras')),
                ('orc_engenharia', models.BooleanField(default=False, verbose_name='Engenharia')),
                ('orc_equipamentos', models.BooleanField(default=False, verbose_name='Equipamentos')),
                ('orc_locacoes', models.BooleanField(default=False, verbose_name='Locações')),
                ('orc_manutencoes', models.BooleanField(default=False, verbose_name='Manutenções')),
                ('orc_outros', models.CharField(blank=True, max_length=150, null=True, verbose_name='Outro Tipo de Orçamento')),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('local_atividade', models.CharField(max_length=200)),
                ('capacidade_fabrica', models.CharField(max_length=100, verbose_name='Capacidade Fábrica (T/h)')),
                ('produto', models.CharField(max_length=150)),
                ('densidade', models.CharField(blank=True, max_length=100, null=True)),
                ('granulometria', models.CharField(blank=True, max_length=100, null=True)),
                ('umidade', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_frete', models.CharField(choices=[('CIF', 'CIF'), ('FOB', 'FOB'), ('OUTROS', 'Outros')], default='CIF', max_length=10)),
                ('tipo_frete_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('eletrica_automacao', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10)),
                ('eletrica_automacao_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('civil', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10)),
                ('civil_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('montagem_campo', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10)),
                ('montagem_campo_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('equipamento_icamento', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10)),
                ('equipamento_icamento_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('pneumatica', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10)),
                ('pneumatica_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('despoeiramento', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10)),
                ('despoeiramento_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('instrumentos', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10)),
                ('instrumentos_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('destelhamento', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10, verbose_name='Destelhamento e Telhamento')),
                ('destelhamento_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('jateamento_pintura', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OUTROS', 'Outros')], default='SIM', max_length=10, verbose_name='Jateamento e Pintura em Campo')),
                ('jateamento_pintura_outros', models.CharField(blank=True, max_length=150, null=True)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais do Escopo')),
                ('risco_capacidade_financeira', models.BooleanField(default=True, verbose_name='Capacidade Financeira')),
                ('risco_fabril', models.BooleanField(default=True, verbose_name='Fabril e Capacidade de Produção')),
                ('risco_qualidade', models.BooleanField(default=True, verbose_name='Qualidade')),
                ('risco_requisitos_legais', models.BooleanField(default=True, verbose_name='Requisitos Legais e Estatutários')),
                ('risco_outros', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outros Riscos, Qual?')),
                ('mkt_indicacao', models.BooleanField(default=False, verbose_name='Indicação')),
                ('mkt_linkedin', models.BooleanField(default=False, verbose_name='LinkedIn')),
                ('mkt_site', models.BooleanField(default=False, verbose_name='Site')),
                ('mkt_instagram', models.BooleanField(default=False, verbose_name='Instagram')),
                ('mkt_outros', models.CharField(blank=True, max_length=150, null=True, verbose_name='Outros (Como conheceu)')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stos_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='STOImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='sto_imagens/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição da Foto (Opcional)')),
                ('sto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='comercial.sto')),
            ],
        ),
    ]
