# Generated by Django 6.0.2 on 2026-02-27 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoFormularioSTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=50, verbose_name='Número da Versão (Ex: Versão 3)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início da Vigência')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Final da Vigência')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='sto',
            name='versao_formulario',
            field=models.CharField(default='Versão 1', max_length=20, verbose_name='Versão do Formulário STO'),
        ),
        migrations.CreateModel(
            name='STORevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Solicitante da Alteração')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('sto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_revisoes', to='comercial.sto')),
                ('usuario_modificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
