# Generated by Django 6.0.2 on 2026-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_versaoformulariosto_sto_versao_formulario_storevisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevisao',
            name='motivo_alteracao',
            field=models.TextField(default='', verbose_name='Descrição da Alteração'),
        ),
    ]
