# Generated by Django 6.0.2 on 2026-04-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_storevisao_motivo_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código da STO'),
        ),
        migrations.AlterField(
            model_name='sto',
            name='risco_capacidade_financeira',
            field=models.BooleanField(default=False, verbose_name='Capacidade Financeira'),
        ),
        migrations.AlterField(
            model_name='sto',
            name='risco_fabril',
            field=models.BooleanField(default=False, verbose_name='Fabril e Capacidade de Produção'),
        ),
        migrations.AlterField(
            model_name='sto',
            name='risco_qualidade',
            field=models.BooleanField(default=False, verbose_name='Qualidade'),
        ),
        migrations.AlterField(
            model_name='sto',
            name='risco_requisitos_legais',
            field=models.BooleanField(default=False, verbose_name='Requisitos Legais e Estatutários'),
        ),
    ]
