# Generated by Django 6.0.2 on 2026-04-01 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Equipamento')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Local/Setor')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('projeto_cod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Projeto')),
                ('elemento_rastreador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Elemento Rastreador')),
                ('detector', models.CharField(choices=[('CL', 'Cliente'), ('IN', 'Interno'), ('AI', 'Auditor Interno'), ('AE', 'Auditor Externo'), ('FO', 'Fornecedor')], max_length=2, verbose_name='Detector')),
                ('categoria', models.CharField(choices=[('CO', 'Comercial'), ('EN', 'Engenharia'), ('PC', 'PCP'), ('FA', 'Fabricação'), ('MO', 'Montagem'), ('SU', 'Suprimentos'), ('FO', 'Fornecedor'), ('EX', 'Expedição'), ('QU', 'Qualidade'), ('RH', 'Recursos Humanos'), ('FI', 'Financeiro'), ('SG', 'SGQ')], default='CO', max_length=2, verbose_name='Categoria da NC')),
                ('criticidade', models.CharField(choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo')], max_length=1, verbose_name='Nível de Criticidade')),
                ('status', models.CharField(choices=[('NI', 'Não iniciada'), ('EA', 'Em andamento'), ('CO', 'Concluído'), ('FT', 'Fora dos trilhos'), ('PR', 'Registro preliminar'), ('CA', 'Cancelado')], default='PR', max_length=2, verbose_name='Status')),
                ('origem', models.CharField(choices=[('CO', 'Comercial'), ('PE', 'Projeto_Engenharia'), ('FA', 'Fabricação'), ('MC', 'Montagem_comissionamento'), ('SU', 'Suprimentos'), ('RH', 'RH'), ('FO', 'Fornecedor'), ('SG', 'Processo_interno_SGQ')], default='CO', max_length=2, verbose_name='Origem')),
                ('descricao', models.TextField(verbose_name='Descrição da Não Conformidade')),
                ('correcao', models.TextField(blank=True, null=True, verbose_name='Correção Imediata')),
                ('ishikawa_link', models.URLField(blank=True, null=True, verbose_name='Diagrama Ishikawa (Link)')),
                ('causas_principais', models.TextField(blank=True, null=True, verbose_name='Principais Causas')),
                ('acao_corretiva', models.TextField(blank=True, null=True, verbose_name='Ação Corretiva')),
                ('eficacia_texto', models.TextField(blank=True, null=True, verbose_name='Verificação de Eficácia (Texto)')),
                ('eficacia_pdf', models.FileField(blank=True, null=True, upload_to='qualidade/rnc/pdfs/', verbose_name='Mídia da Verificação (PDF)')),
                ('data_prevista_conclusao', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Conclusão')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão do Registro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualidade.equipamento', verbose_name='Equipamento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qualidade.local', verbose_name='Local')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rncs_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='rncs_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name': 'Registro de Não Conformidade',
                'verbose_name_plural': 'Registros de Não Conformidade',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RNCEficaciaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens_eficacia', models.ImageField(upload_to='qualidade/rnc/eficacia', verbose_name='Anexo de Imagem Eficacia')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('rnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficacia_imagens', to='qualidade.rnc')),
            ],
            options={
                'verbose_name': 'Imagem Eficacia da RNC',
                'verbose_name_plural': 'Imagens da Eficacia das RNCs',
            },
        ),
        migrations.CreateModel(
            name='RNCImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='qualidade/rnc/imagens/', verbose_name='Anexo de Imagem')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('rnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='qualidade.rnc')),
            ],
            options={
                'verbose_name': 'Imagem da RNC',
                'verbose_name_plural': 'Imagens da RNC',
            },
        ),
    ]
