# Generated by Django 6.0.2 on 2026-04-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNCEficaciaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens_eficacia', models.ImageField(upload_to='qualidade/rnc/eficacia', verbose_name='Anexo de Imagem Eficacia')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('rnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficacia_imagens', to='qualidade.rnc')),
            ],
            options={
                'verbose_name': 'Imagem Eficacia da RNC',
                'verbose_name_plural': 'Imagens da Eficacia das RNCs',
            },
        ),
        migrations.CreateModel(
            name='RNCImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='qualidade/rnc/imagens/', verbose_name='Anexo de Imagem')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('rnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='qualidade.rnc')),
            ],
            options={
                'verbose_name': 'Imagem da RNC',
                'verbose_name_plural': 'Imagens da RNC',
            },
        ),
    ]
