# Generated by Django 6.0.2 on 2026-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_rnceficaciaimagem_rncimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnc',
            name='ishikawa_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Diagrama Ishikawa (Link)'),
        ),
    ]
