# Generated by Django 6.0.2 on 2026-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0003_rnceficaciaimagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnc',
            name='tipo_nc',
        ),
        migrations.RemoveField(
            model_name='rnc',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='rnc',
            name='justificativa_criticidade',
        ),
        migrations.AddField(
            model_name='rnc',
            name='categoria',
            field=models.CharField(choices=[('SI', 'Sistema'), ('PR', 'Produto'), ('PO', 'Processo'), ('CO', 'Comercial'), ('EN', 'Engenharia'), ('PC', 'PCP'), ('FA', 'Fabricação'), ('MO', 'Montagem'), ('SU', 'Suprimentos'), ('FO', 'Fornecedor'), ('EX', 'Expedição'), ('QU', 'Qualidade'), ('RH', 'Recursos Humanos'), ('FI', 'Financeiro'), ('SG', 'SGQ')], default='SI', max_length=2, verbose_name='Categoria da NC'),
        ),
        migrations.DeleteModel(
            name='TipoNC',
        ),
    ]
