# Generated by Django 6.0.2 on 2026-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0003_alter_rnc_ishikawa_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnc',
            name='categoria',
            field=models.CharField(choices=[('CO', 'Comercial'), ('PE', 'Projeto / Engenharia'), ('PC', 'PCP'), ('FA', 'Fabricação'), ('MO', 'Obra / Montagem'), ('SU', 'Suprimentos'), ('FO', 'Fornecedor Externo'), ('EX', 'Recebimento / Expedição'), ('QU', 'Qualidade'), ('RH', 'Recursos Humanos'), ('FI', 'Financeiro'), ('SG', 'SGQ'), ('PJ', 'Planejamento / Cronograma')], default='CO', max_length=2, verbose_name='Categoria da NC'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='origem',
            field=models.CharField(choices=[('CO', 'Comercial'), ('PE', 'Projeto / Engenharia'), ('FA', 'Fabricação'), ('MC', 'Montagem / Comissionamento'), ('SU', 'Suprimentos'), ('RH', 'RH'), ('FO', 'Fornecedor'), ('SG', 'Processo_interno_SGQ'), ('GR', 'Geral')], default='CO', max_length=2, verbose_name='Origem'),
        ),
    ]
