# Generated by Django 6.0.2 on 2026-03-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0004_remove_rnc_tipo_nc_remove_rnc_classificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnc',
            name='origem',
            field=models.CharField(choices=[('CO', 'Comercial'), ('PE', 'Projeto_Engenharia'), ('FA', 'Fabricação'), ('MC', 'Montagem_comissionamento'), ('SU', 'Suprimentos'), ('RH', 'RH'), ('FO', 'Fornecedor'), ('SG', 'Processo_interno_SGQ')], default='CO', max_length=2, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='categoria',
            field=models.CharField(choices=[('CO', 'Comercial'), ('EN', 'Engenharia'), ('PC', 'PCP'), ('FA', 'Fabricação'), ('MO', 'Montagem'), ('SU', 'Suprimentos'), ('FO', 'Fornecedor'), ('EX', 'Expedição'), ('QU', 'Qualidade'), ('RH', 'Recursos Humanos'), ('FI', 'Financeiro'), ('SG', 'SGQ')], default='CO', max_length=2, verbose_name='Categoria da NC'),
        ),
    ]
