# Generated by Django 6.0.2 on 2026-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0004_alter_rnc_categoria_alter_rnc_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnc',
            name='categoria',
            field=models.CharField(choices=[('CO', 'Comercial'), ('PE', 'Projeto / Engenharia'), ('PC', 'PCP'), ('FA', 'Fabricação'), ('MO', 'Obra / Montagem'), ('MC', 'Montagem / Comissionamento'), ('SU', 'Suprimentos'), ('FO', 'Fornecedor Externo'), ('EX', 'Recebimento / Expedição'), ('QU', 'Qualidade'), ('RH', 'Recursos Humanos'), ('FI', 'Financeiro'), ('SG', 'SGQ'), ('PJ', 'Planejamento / Cronograma'), ('PR', 'Processo'), ('RC', 'Requisitos contratuais'), ('RN', 'Requisitos normas'), ('SI', 'Sistema')], default='CO', max_length=2, verbose_name='Categoria da NC'),
        ),
    ]
