# Generated by Django 6.0.2 on 2026-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0005_alter_rnc_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnc',
            name='status',
            field=models.CharField(choices=[('NI', 'Não iniciada'), ('EA', 'Em andamento'), ('CO', 'Concluído'), ('PR', 'Registro preliminar'), ('CA', 'Cancelado')], default='PR', max_length=2, verbose_name='Status'),
        ),
    ]
