# Generated by Django 4.2.30 on 2026-05-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0006_alter_rnc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnc',
            name='eficacia_pdf',
        ),
        migrations.CreateModel(
            name='RNCEficaciaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(upload_to='qualidade/rnc/pdfs/', verbose_name='Anexo PDF Eficacia')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('rnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficacia_pdfs', to='qualidade.rnc')),
            ],
            options={
                'verbose_name': 'PDF Eficácia da RNC',
                'verbose_name_plural': 'PDF Eficácias da RNCs',
            },
        ),
    ]
