# Generated by Django 4.2.30 on 2026-05-20 15:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('local', models.CharField(max_length=200)),
                ('contrato', models.CharField(blank=True, max_length=80)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('PARALISADA', 'Paralisada'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('condicao_climatica', models.CharField(blank=True, choices=[('ENSOLARADO', 'Ensolarado'), ('NUBLADO', 'Nublado'), ('CHUVOSO', 'Chuvoso'), ('VENTO_FORTE', 'Vento forte'), ('PARCIALMENTE_NUBLADO', 'Parcialmente nublado')], max_length=30)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdos', to='rdo.obra')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RDO',
                'verbose_name_plural': 'RDOs',
                'ordering': ['-data', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEGURANCA', 'Seguranca'), ('QUALIDADE', 'Qualidade'), ('CLIMA', 'Clima'), ('SUPRIMENTOS', 'Suprimentos'), ('EQUIPAMENTO', 'Equipamento'), ('OUTROS', 'Outros')], max_length=30)),
                ('descricao', models.TextField()),
                ('impacto', models.TextField(blank=True)),
                ('providencia', models.TextField(blank=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='rdo.rdo')),
            ],
            options={
                'verbose_name': 'Ocorrencia do RDO',
                'verbose_name_plural': 'Ocorrencias dos RDOs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FotoRDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='rdo/fotos/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='rdo.rdo')),
            ],
            options={
                'verbose_name': 'Foto do RDO',
                'verbose_name_plural': 'Fotos dos RDOs',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoRDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=120)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('horas_utilizadas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('OPERANDO', 'Operando'), ('PARADO', 'Parado'), ('MANUTENCAO', 'Em manutencao')], default='OPERANDO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='rdo.rdo')),
            ],
            options={
                'verbose_name': 'Equipamento do RDO',
                'verbose_name_plural': 'Equipamentos dos RDOs',
                'ordering': ['equipamento'],
            },
        ),
        migrations.CreateModel(
            name='EfetivoRDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivos', to='rdo.rdo')),
            ],
            options={
                'verbose_name': 'Efetivo do RDO',
                'verbose_name_plural': 'Efetivos dos RDOs',
                'ordering': ['funcao'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeRDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('local_execucao', models.CharField(blank=True, max_length=150)),
                ('percentual_avanco', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observacoes', models.TextField(blank=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='rdo.rdo')),
            ],
            options={
                'verbose_name': 'Atividade do RDO',
                'verbose_name_plural': 'Atividades dos RDOs',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rdo',
            constraint=models.UniqueConstraint(fields=('obra', 'numero'), name='rdo_obra_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='rdo',
            constraint=models.UniqueConstraint(fields=('obra', 'data'), name='rdo_obra_data_unica'),
        ),
    ]
