# Generated by Django 4.2.30 on 2026-05-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotordo',
            name='imagem_pdf',
            field=models.ImageField(blank=True, upload_to='rdo/fotos_pdf/%Y/%m/'),
        ),
    ]
