# Generated by Django 4.2.30 on 2026-05-21 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from datetime import timedelta


def decimal_hours_to_duration(value):
    if value is None:
        return None
    minutes = int(round(float(value) * 60))
    return timedelta(minutes=minutes)


def duration_to_decimal_hours(value):
    if value is None:
        return None
    return round(value.total_seconds() / 3600, 2)


def migrate_duration_fields(apps, schema_editor):
    EfetivoRDO = apps.get_model('rdo', 'EfetivoRDO')
    EquipamentoRDO = apps.get_model('rdo', 'EquipamentoRDO')
    for efetivo in EfetivoRDO.objects.all().iterator():
        efetivo.horas_trabalhadas = decimal_hours_to_duration(efetivo.horas_trabalhadas_decimal)
        efetivo.save(update_fields=['horas_trabalhadas'])
    for equipamento in EquipamentoRDO.objects.all().iterator():
        equipamento.horas_utilizadas = decimal_hours_to_duration(equipamento.horas_utilizadas_decimal)
        equipamento.save(update_fields=['horas_utilizadas'])


def reverse_duration_fields(apps, schema_editor):
    EfetivoRDO = apps.get_model('rdo', 'EfetivoRDO')
    EquipamentoRDO = apps.get_model('rdo', 'EquipamentoRDO')
    for efetivo in EfetivoRDO.objects.all().iterator():
        efetivo.horas_trabalhadas_decimal = duration_to_decimal_hours(efetivo.horas_trabalhadas)
        efetivo.save(update_fields=['horas_trabalhadas_decimal'])
    for equipamento in EquipamentoRDO.objects.all().iterator():
        equipamento.horas_utilizadas_decimal = duration_to_decimal_hours(equipamento.horas_utilizadas)
        equipamento.save(update_fields=['horas_utilizadas_decimal'])


def copy_legacy_weather_and_uppercase_obras(apps, schema_editor):
    Obra = apps.get_model('rdo', 'Obra')
    RDO = apps.get_model('rdo', 'RDO')
    for obra in Obra.objects.all().iterator():
        nome = (obra.nome or '').upper()
        if obra.nome != nome:
            obra.nome = nome
            obra.save(update_fields=['nome'])
    for rdo in RDO.objects.exclude(condicao_climatica='').iterator():
        rdo.condicao_manha = rdo.condicao_climatica
        rdo.condicao_tarde = rdo.condicao_climatica
        rdo.condicao_noite = rdo.condicao_climatica
        rdo.save(update_fields=['condicao_manha', 'condicao_tarde', 'condicao_noite'])


class Migration(migrations.Migration):

    dependencies = [
        ('rdo', '0002_fotordo_imagem_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivordo',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='data_previsao_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='logo_cliente',
            field=models.ImageField(blank=True, upload_to='rdo/clientes/logos/'),
        ),
        migrations.AddField(
            model_name='obra',
            name='responsavel_cliente',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='obra',
            name='responsavel_i9',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rdo',
            name='condicao_manha',
            field=models.CharField(choices=[('NAO_SE_APLICA', 'Nao se aplica'), ('ENSOLARADO', 'Ensolarado'), ('NUBLADO', 'Nublado'), ('CHUVOSO', 'Chuvoso'), ('VENTO_FORTE', 'Vento forte'), ('PARCIALMENTE_NUBLADO', 'Parcialmente nublado')], default='NAO_SE_APLICA', max_length=30),
        ),
        migrations.AddField(
            model_name='rdo',
            name='condicao_noite',
            field=models.CharField(choices=[('NAO_SE_APLICA', 'Nao se aplica'), ('ENSOLARADO', 'Ensolarado'), ('NUBLADO', 'Nublado'), ('CHUVOSO', 'Chuvoso'), ('VENTO_FORTE', 'Vento forte'), ('PARCIALMENTE_NUBLADO', 'Parcialmente nublado')], default='NAO_SE_APLICA', max_length=30),
        ),
        migrations.AddField(
            model_name='rdo',
            name='condicao_tarde',
            field=models.CharField(choices=[('NAO_SE_APLICA', 'Nao se aplica'), ('ENSOLARADO', 'Ensolarado'), ('NUBLADO', 'Nublado'), ('CHUVOSO', 'Chuvoso'), ('VENTO_FORTE', 'Vento forte'), ('PARCIALMENTE_NUBLADO', 'Parcialmente nublado')], default='NAO_SE_APLICA', max_length=30),
        ),
        migrations.RunPython(copy_legacy_weather_and_uppercase_obras, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='atividaderdo',
            name='percentual_avanco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='efetivordo',
            name='funcao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RenameField(
            model_name='efetivordo',
            old_name='horas_trabalhadas',
            new_name='horas_trabalhadas_decimal',
        ),
        migrations.AddField(
            model_name='efetivordo',
            name='horas_trabalhadas',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamentordo',
            name='equipamento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RenameField(
            model_name='equipamentordo',
            old_name='horas_utilizadas',
            new_name='horas_utilizadas_decimal',
        ),
        migrations.AddField(
            model_name='equipamentordo',
            name='horas_utilizadas',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_duration_fields, reverse_duration_fields),
        migrations.RemoveField(
            model_name='efetivordo',
            name='horas_trabalhadas_decimal',
        ),
        migrations.RemoveField(
            model_name='equipamentordo',
            name='horas_utilizadas_decimal',
        ),
        migrations.AlterField(
            model_name='rdo',
            name='condicao_climatica',
            field=models.CharField(blank=True, choices=[('NAO_SE_APLICA', 'Nao se aplica'), ('ENSOLARADO', 'Ensolarado'), ('NUBLADO', 'Nublado'), ('CHUVOSO', 'Chuvoso'), ('VENTO_FORTE', 'Vento forte'), ('PARCIALMENTE_NUBLADO', 'Parcialmente nublado')], max_length=30),
        ),
        migrations.CreateModel(
            name='FuncaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='rdo.obra')),
            ],
            options={
                'verbose_name': 'Funcao da obra',
                'verbose_name_plural': 'Funcoes da obra',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_disponiveis', to='rdo.obra')),
            ],
            options={
                'verbose_name': 'Equipamento da obra',
                'verbose_name_plural': 'Equipamentos da obra',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='efetivordo',
            name='funcao_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_rdo', to='rdo.funcaoobra'),
        ),
        migrations.AddField(
            model_name='equipamentordo',
            name='equipamento_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_rdo', to='rdo.equipamentoobra'),
        ),
        migrations.AddConstraint(
            model_name='funcaoobra',
            constraint=models.UniqueConstraint(fields=('obra', 'nome'), name='funcao_obra_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='equipamentoobra',
            constraint=models.UniqueConstraint(fields=('obra', 'nome'), name='equipamento_obra_nome_unico'),
        ),
    ]
