# Generated by Django 4.2.30 on 2026-05-26 16:38

from django.db import migrations, models
import django.db.models.deletion


FUNCOES_PADRAO = [
    'Encanador',
    'Soldador',
    'Ajudante',
    'Eletricista',
    'Mecanico',
    'Tecnico de Seguranca',
]


def _get_or_create_funcao(Funcao, nome, ativo=True):
    nome = (nome or '').strip()
    if not nome:
        return None
    funcao = Funcao.objects.filter(nome__iexact=nome).first()
    if funcao:
        if ativo and not funcao.ativo:
            funcao.ativo = True
            funcao.save(update_fields=['ativo'])
        return funcao
    return Funcao.objects.create(nome=nome, ativo=ativo)


def migrar_funcoes_padrao(apps, schema_editor):
    Funcao = apps.get_model('rdo', 'Funcao')
    FuncaoObra = apps.get_model('rdo', 'FuncaoObra')
    EfetivoRDO = apps.get_model('rdo', 'EfetivoRDO')
    Obra = apps.get_model('rdo', 'Obra')
    ObraFuncao = Obra._meta.get_field('funcoes').remote_field.through

    for nome in FUNCOES_PADRAO:
        _get_or_create_funcao(Funcao, nome, ativo=True)

    funcao_por_legacy_id = {}
    for funcao_obra in FuncaoObra.objects.select_related('obra').all().iterator():
        funcao = _get_or_create_funcao(Funcao, funcao_obra.nome, ativo=funcao_obra.ativo)
        if not funcao:
            continue
        funcao_por_legacy_id[funcao_obra.pk] = funcao.pk
        ObraFuncao.objects.get_or_create(obra_id=funcao_obra.obra_id, funcao_id=funcao.pk)

    for efetivo in EfetivoRDO.objects.exclude(funcao_cadastro_id__isnull=True).iterator():
        funcao_id = funcao_por_legacy_id.get(efetivo.funcao_cadastro_id)
        if funcao_id:
            efetivo.funcao_padrao_id = funcao_id
            efetivo.save(update_fields=['funcao_padrao'])

    obras_com_funcoes = set(ObraFuncao.objects.values_list('obra_id', flat=True))
    for obra in Obra.objects.exclude(pk__in=obras_com_funcoes).iterator():
        for nome in FUNCOES_PADRAO:
            funcao = _get_or_create_funcao(Funcao, nome, ativo=True)
            ObraFuncao.objects.get_or_create(obra_id=obra.pk, funcao_id=funcao.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('rdo', '0003_efetivordo_horario_entrada_obra_data_previsao_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funcao',
                'verbose_name_plural': 'Funcoes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='funcao',
            constraint=models.UniqueConstraint(fields=('nome',), name='funcao_nome_unico'),
        ),
        migrations.AddField(
            model_name='obra',
            name='funcoes',
            field=models.ManyToManyField(blank=True, related_name='obras', to='rdo.funcao'),
        ),
        migrations.AddField(
            model_name='efetivordo',
            name='funcao_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_rdo_padrao', to='rdo.funcao'),
        ),
        migrations.RunPython(migrar_funcoes_padrao, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='efetivordo',
            name='funcao_cadastro',
        ),
        migrations.RenameField(
            model_name='efetivordo',
            old_name='funcao_padrao',
            new_name='funcao_cadastro',
        ),
        migrations.AlterField(
            model_name='efetivordo',
            name='funcao_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efetivos_rdo', to='rdo.funcao'),
        ),
        migrations.DeleteModel(
            name='FuncaoObra',
        ),
    ]
