# Generated by Django 4.2.30 on 2026-05-26 16:46

from django.db import migrations, models
import django.db.models.deletion


def _get_or_create_equipamento(Equipamento, nome, ativo=True):
    nome = (nome or '').strip()
    if not nome:
        return None
    equipamento = Equipamento.objects.filter(nome__iexact=nome).first()
    if equipamento:
        if ativo and not equipamento.ativo:
            equipamento.ativo = True
            equipamento.save(update_fields=['ativo'])
        return equipamento
    return Equipamento.objects.create(nome=nome, ativo=ativo)


def migrar_equipamentos_padrao(apps, schema_editor):
    Equipamento = apps.get_model('rdo', 'Equipamento')
    EquipamentoObra = apps.get_model('rdo', 'EquipamentoObra')
    EquipamentoRDO = apps.get_model('rdo', 'EquipamentoRDO')
    Obra = apps.get_model('rdo', 'Obra')
    ObraEquipamento = Obra._meta.get_field('equipamentos').remote_field.through

    equipamento_por_legacy_id = {}
    for equipamento_obra in EquipamentoObra.objects.select_related('obra').all().iterator():
        equipamento = _get_or_create_equipamento(Equipamento, equipamento_obra.nome, ativo=equipamento_obra.ativo)
        if not equipamento:
            continue
        equipamento_por_legacy_id[equipamento_obra.pk] = equipamento.pk
        ObraEquipamento.objects.get_or_create(obra_id=equipamento_obra.obra_id, equipamento_id=equipamento.pk)

    for equipamento_rdo in EquipamentoRDO.objects.exclude(equipamento_cadastro_id__isnull=True).iterator():
        equipamento_id = equipamento_por_legacy_id.get(equipamento_rdo.equipamento_cadastro_id)
        if equipamento_id:
            equipamento_rdo.equipamento_padrao_id = equipamento_id
            equipamento_rdo.save(update_fields=['equipamento_padrao'])


class Migration(migrations.Migration):

    dependencies = [
        ('rdo', '0004_padronizar_funcoes_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(fields=('nome',), name='equipamento_nome_unico'),
        ),
        migrations.AddField(
            model_name='obra',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='obras', to='rdo.equipamento'),
        ),
        migrations.AddField(
            model_name='equipamentordo',
            name='equipamento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_rdo_padrao', to='rdo.equipamento'),
        ),
        migrations.RunPython(migrar_equipamentos_padrao, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='equipamentordo',
            name='equipamento_cadastro',
        ),
        migrations.RenameField(
            model_name='equipamentordo',
            old_name='equipamento_padrao',
            new_name='equipamento_cadastro',
        ),
        migrations.AlterField(
            model_name='equipamentordo',
            name='equipamento_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_rdo', to='rdo.equipamento'),
        ),
        migrations.DeleteModel(
            name='EquipamentoObra',
        ),
    ]
