# Generated by Django 6.0.2 on 2026-03-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawarehousecompras',
            name='data_prev_recebimento_fisico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datawarehousecompras',
            name='data_recebimento_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datawarehousecompras',
            name='emissao_pedido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datawarehousecompras',
            name='emissao_sc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
