# Generated by Django 6.0.2 on 2026-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_datawarehousecompras_data_prev_recebimento_fisico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(blank=True, max_length=20, null=True)),
                ('num_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('item_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('projeto_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('tarefa_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('num_pedidos_vinculados', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('status_operacional', models.CharField(blank=True, max_length=50, null=True)),
                ('emissao_sc', models.DateField(blank=True, null=True)),
                ('emissao_ultimo_pedido', models.DateField(blank=True, null=True)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('ultima_entrega_real', models.DateField(blank=True, null=True)),
                ('qtd_solicitada', models.FloatField(default=0)),
                ('qtd_pedida', models.FloatField(default=0)),
                ('qtd_recebida', models.FloatField(default=0)),
                ('saldo_a_comprar', models.FloatField(default=0)),
                ('saldo_a_receber', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Operação de Compras',
                'verbose_name_plural': 'Operações de Compras',
            },
        ),
    ]
