# Generated by Django 6.0.2 on 2026-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_operacaocompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocompras',
            name='notas_fiscais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
