# Generated by Django 6.0.2 on 2026-04-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_operacaocompras_notas_fiscais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaocompras',
            old_name='saldo_a_receber',
            new_name='qtd_a_receber',
        ),
    ]
