# Generated by Django 6.0.2 on 2026-04-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_rename_saldo_a_receber_operacaocompras_qtd_a_receber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacaocompras',
            old_name='qtd_a_receber',
            new_name='residuo',
        ),
    ]
