# Generated by Django 6.0.2 on 2026-05-08 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_rename_qtd_a_receber_operacaocompras_residuo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='operacaocompras',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='operacaocompras',
            name='tipo_produto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Produto'),
        ),
        migrations.CreateModel(
            name='AvaliacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pedido', models.CharField(max_length=50)),
                ('cod_fornecedor', models.CharField(max_length=50)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('projeto', models.CharField(max_length=20)),
                ('tipo_produto', models.CharField(max_length=50)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(0, '0 - Não Atendeu'), (10, '10 - Atendeu Totalmente')], default=0)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='compras.avaliacaofornecedor')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.perguntaavaliacao')),
            ],
        ),
    ]
