# Generated by Django 4.2.30 on 2026-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_perguntaavaliacao_operacaocompras_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('arquivos_processados', models.JSONField(blank=True, default=list)),
                ('linhas_lidas', models.PositiveIntegerField(default=0)),
                ('linhas_gravadas', models.PositiveIntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('erro', models.TextField(blank=True, default='')),
                ('executado_por', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Log de Sincronização de Compras',
                'verbose_name_plural': 'Logs de Sincronização de Compras',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='PmsCustoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=20)),
                ('projeto', models.CharField(max_length=50)),
                ('revisao', models.CharField(max_length=20)),
                ('edt', models.CharField(blank=True, default='', max_length=50)),
                ('tarefa', models.CharField(max_length=50)),
                ('custo_previsto', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('custo_previsto_produtos', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('custo_previsto_despesas', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('custo_previsto_detalhado', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('custo_realizado', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('custo_empenhado', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('saldo_previsto_realizado', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('variacao_percentual', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custo PMS por Tarefa',
                'verbose_name_plural': 'Custos PMS por Tarefa',
            },
        ),
        migrations.CreateModel(
            name='PmsEdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=20)),
                ('projeto', models.CharField(max_length=50)),
                ('revisao', models.CharField(max_length=20)),
                ('edt', models.CharField(max_length=50)),
                ('edt_pai', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('nivel', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem', models.CharField(blank=True, default='', max_length=50)),
                ('unidade', models.CharField(blank=True, default='', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('custo_previsto', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EDT PMS',
                'verbose_name_plural': 'EDTs PMS',
            },
        ),
        migrations.CreateModel(
            name='PmsProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=20)),
                ('projeto', models.CharField(max_length=50)),
                ('revisao', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('data_base', models.DateField(blank=True, null=True)),
                ('calendario', models.CharField(blank=True, default='', max_length=50)),
                ('mascara', models.CharField(blank=True, default='', max_length=50)),
                ('delimitador', models.CharField(blank=True, default='', max_length=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto PMS',
                'verbose_name_plural': 'Projetos PMS',
            },
        ),
        migrations.CreateModel(
            name='PmsTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=20)),
                ('projeto', models.CharField(max_length=50)),
                ('revisao', models.CharField(max_length=20)),
                ('tarefa', models.CharField(max_length=50)),
                ('edt', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('nivel', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem', models.CharField(blank=True, default='', max_length=50)),
                ('unidade', models.CharField(blank=True, default='', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('data_inicio_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('custo_previsto', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarefa PMS',
                'verbose_name_plural': 'Tarefas PMS',
                'indexes': [models.Index(fields=['projeto', 'revisao', 'tarefa'], name='compras_pms_projeto_be1a6b_idx'), models.Index(fields=['filial', 'projeto', 'revisao', 'edt'], name='compras_pms_filial_7f44af_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pmstarefa',
            constraint=models.UniqueConstraint(fields=('filial', 'projeto', 'revisao', 'tarefa'), name='uniq_pms_tarefa_revisao'),
        ),
        migrations.AddIndex(
            model_name='pmsprojeto',
            index=models.Index(fields=['projeto', 'revisao'], name='compras_pms_projeto_b9f024_idx'),
        ),
        migrations.AddIndex(
            model_name='pmsprojeto',
            index=models.Index(fields=['filial', 'projeto', 'revisao'], name='compras_pms_filial_c2ba2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='pmsprojeto',
            constraint=models.UniqueConstraint(fields=('filial', 'projeto', 'revisao'), name='uniq_pms_projeto_revisao'),
        ),
        migrations.AddIndex(
            model_name='pmsedt',
            index=models.Index(fields=['projeto', 'revisao', 'edt'], name='compras_pms_projeto_837346_idx'),
        ),
        migrations.AddIndex(
            model_name='pmsedt',
            index=models.Index(fields=['filial', 'projeto', 'revisao', 'edt_pai'], name='compras_pms_filial_29a22e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pmsedt',
            constraint=models.UniqueConstraint(fields=('filial', 'projeto', 'revisao', 'edt'), name='uniq_pms_edt_revisao'),
        ),
        migrations.AddIndex(
            model_name='pmscustotarefa',
            index=models.Index(fields=['projeto', 'revisao', 'tarefa'], name='compras_pms_projeto_e9d483_idx'),
        ),
        migrations.AddIndex(
            model_name='pmscustotarefa',
            index=models.Index(fields=['filial', 'projeto', 'revisao', 'edt'], name='compras_pms_filial_807a70_idx'),
        ),
        migrations.AddConstraint(
            model_name='pmscustotarefa',
            constraint=models.UniqueConstraint(fields=('filial', 'projeto', 'revisao', 'tarefa'), name='uniq_pms_custo_tarefa_revisao'),
        ),
        migrations.AddIndex(
            model_name='comprassynclog',
            index=models.Index(fields=['nome', 'status'], name='compras_com_nome_5c3b30_idx'),
        ),
        migrations.AddIndex(
            model_name='comprassynclog',
            index=models.Index(fields=['-iniciado_em'], name='compras_com_iniciad_f9fcd9_idx'),
        ),
    ]
