# Generated by Django 4.2.30 on 2026-06-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_pms_dashboard_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataWarehouseCompras',
        ),
    ]
