# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_delete_datawarehousecompras'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmsCustoTemporalMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=20)),
                ('projeto', models.CharField(max_length=50)),
                ('revisao', models.CharField(max_length=20)),
                ('edt', models.CharField(blank=True, default='', max_length=50)),
                ('tarefa', models.CharField(max_length=50)),
                ('competencia', models.DateField()),
                ('custo_empenhado', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('custo_realizado', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custo PMS Temporal Mensal',
                'verbose_name_plural': 'Custos PMS Temporais Mensais',
                'indexes': [
                    models.Index(fields=['projeto', 'revisao', 'competencia'], name='compras_pms_projeto_comp_idx'),
                    models.Index(fields=['filial', 'projeto', 'revisao', 'edt', 'competencia'], name='compras_pms_edt_comp_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('filial', 'projeto', 'revisao', 'tarefa', 'competencia'), name='uniq_pms_custo_temporal'),
                ],
            },
        ),
    ]
