# Generated by Django 4.2.30 on 2026-05-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0002_alter_estruturaproduto_codigo_componente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estruturaproduto',
            options={'verbose_name': 'Estrutura e Produção', 'verbose_name_plural': 'Estruturas e Produção'},
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='base_estrutural',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='codigo_componente',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='descricao_componente',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='fim_validade',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='grupo_componente',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='grupo_pai',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='inicio_validade',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='perda_percentual',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='quantidade_necessaria',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='tipo_componente',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='tipo_pai',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='tipo_quantidade',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='unidade_medida_filho',
        ),
        migrations.RemoveField(
            model_name='estruturaproduto',
            name='unidade_pai',
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='codigo_filho',
            field=models.CharField(db_index=True, default=0.0, max_length=50, verbose_name='Código filho'),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='codigo_vo',
            field=models.CharField(db_index=True, default=0.0, max_length=50, verbose_name='Código Vo'),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='descricao_filho',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição filho'),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='descricao_vo',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição Vo'),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='falta_produzir',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Falta Produzir'),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='quantidade_em_op',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Quantidade em OP'),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='quantidade_necessaria_filho',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Qtd Necessária'),
        ),
        migrations.AlterField(
            model_name='estruturaproduto',
            name='codigo_pai',
            field=models.CharField(db_index=True, default=0.0, max_length=50, verbose_name='Código Pai'),
        ),
        migrations.AlterField(
            model_name='estruturaproduto',
            name='descricao_pai',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição Pai'),
        ),
    ]
