name: Deploy Automático para PythonAnywhere

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Executar Atualização via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh.pythonanywhere.com
          username: ${{ secrets.PA_USERNAME }}
          key: ${{ secrets.PA_SSH_KEY }}
          script: |
            # Entra na pasta do projeto
            cd /home/${{ secrets.PA_USERNAME }}/sistema_i9tmg
            
            # Puxa o código novo do GitHub
            git pull origin main
            
            # Ativa o ambiente virtual no caminho correto
            source /home/${{ secrets.PA_USERNAME }}/venv/bin/activate
            
            # Instala dependências, roda migrações e coleta estáticos de forma silenciosa
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput

      # Avisa o PythonAnywhere para reiniciar a aplicação via API REST
      - name: Reiniciar a Aplicação Web (Reload WSGI)
        run: |
          curl -X POST \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_DOMAIN }}/reload/ \
            -H "Authorization: Token ${{ secrets.PA_TOKEN }}"